stages:
  - unit-test
  - package
  - deploy-jaws
  - integration-test
  - .post

variables:
  GIT_STRATEGY: clone

  ## GLOBAL INSTALL VARIABLES:
  JAWS_SITES: "CORI JGI CASCADE"
  JAWS_VERSION: "2.0.1"
  JAWS_DOCS_URL: "https://jaws-docs.readthedocs.io/en/latest/"
  JAWS_CENTRAL_HOST: "http://jaws.lbl.gov"
  JAWS_CENTRAL_RMQ_HOST: "rmq.lbl.gov"
  JAWS_CENTRAL_RMQ_PORT: 5672
  JAWS_GLOBUS_CLIENT_ID: "29a47d96-76b4-4f2b-a8bb-a4cb38ea17e3"
  CROMWELL_VERSION: "52"

  ## CENTRAL-SPECIFIC VARIABLES:
  JAWS_CENTRAL_DB_HOST: "jaws-db.lbl.gov"
  JAWS_CENTRAL_DB_PORT: 3306

  ## DEPLOYMENT-SPECIFIC VARIABLES:
  dev_LOG_LEVEL: "DEBUG"
  dev_JAWS_SUPERVISOR_PORT: 64101
  dev_JTM_SUPERVISOR_PORT: 64111
  dev_JAWS_CENTRAL_SUPERVISOR_PORT: 64121
  dev_JAWS_AUTH_PORT: 3001
  dev_JAWS_REST_PORT: 5001
  dev_CROMWELL_PORT: 50101
  staging_LOG_LEVEL: "DEBUG"
  staging_JAWS_SUPERVISOR_PORT: 64102
  staging_JTM_SUPERVISOR_PORT: 64112
  staging_JAWS_CENTRAL_SUPERVISOR_PORT: 64122
  staging_JAWS_AUTH_PORT: 3002
  staging_JAWS_REST_PORT: 5002
  staging_CROMWELL_PORT: 50102
  prod_LOG_LEVEL: "INFO"
  prod_JAWS_SUPERVISOR_PORT: 64103
  prod_JTM_SUPERVISOR_PORT: 64113
  prod_JAWS_CENTRAL_SUPERVISOR_PORT: 64123
  prod_JAWS_AUTH_PORT: 3003
  prod_JAWS_REST_PORT: 5003
  prod_CROMWELL_PORT: 50103

  ## CENTRAL-SPECIFIC VARIABLES:
  CENTRAL_INSTALL_BASEDIR: "/tmp"
  CENTRAL_GLOBUS_EP: "9d6d994a-6d04-11e5-ba46-22000b92c6ec"
  CENTRAL_GLOBUS_ROOT_DIR: "/"
  CENTRAL_GLOBUS_DEFAULT_DIR: "~"
  CENTRAL_RMQ_HOST: "rmq.lbl.gov"
  CENTRAL_RMQ_PORT: 5672
  CENTRAL_PYTHON: "python3"
  CENTRAL_LOAD_PYTHON: ""
  CENTRAL_JAWS_GROUP: "jaws"
  CENTRAL_JAWS_SCRATCH_BASEDIR: "/tmp/jaws-tmp"
  CENTRAL_JAWS_SW_BASEDIR: "/opt/jaws"
  CENTRAL_SUPERVISOR_HOST: "http://jaws.lbl.gov"
  CENTRAL_DB_HOST: "jaws-db.lbl.gov"
  CENTRAL_DB_PORT: 3306

  ## SITE-SPECIFIC VARIABLES:
  CORI_INSTALL_BASEDIR: "/tmp"
  CORI_GLOBUS_EP: "9d6d994a-6d04-11e5-ba46-22000b92c6ec"
  CORI_GLOBUS_ROOT_DIR: "/"
  CORI_GLOBUS_DEFAULT_DIR: "~"
  CORI_RMQ_HOST: "rmq.lbl.gov"
  CORI_RMQ_PORT: 5672
  CORI_PYTHON: "python3"
  CORI_LOAD_PYTHON: "module load python3/3.7-anaconda-2019.10"
  CORI_JAWS_GROUP: "jaws"
  CORI_JTM_GROUP: "jaws_jtm"
  CORI_CLIENT_GROUP: "genome"
  CORI_JAWS_SCRATCH_BASEDIR: "/global/cscratch1/sd/jaws"
  CORI_JTM_SCRATCH_BASEDIR: "/global/cscratch1/sd/jaws_jtm"
  CORI_JAWS_SW_BASEDIR: "/global/cfs/projectdirs/jaws"
  CORI_JTM_SW_BASEDIR: "/global/cfs/projectdirs/jaws_jtm"
  CORI_REF_DATA_DIR: "/global/cscratch1/sd/jaws/refdata"
  CORI_SUPERVISOR_HOST: "http://cori20.nersc.gov"
  CORI_CONTAINER_TYPE: "shifter"
  CORI_DB_HOST: "jaws-db.lbl.gov"
  CORI_DB_PORT: 3306
  CORI_CLUSTER_QOS: "genepool_special"
  CORI_CLUSTER_PARTITION: ""
  CORI_CLUSTER_ACCOUNT: "fungalp"
  CORI_CLUSTER_CONSTRAINT: "haswell"
  CORI_MAX_RAM_GB: 2048
  CORI_LOAD_JAVA: ""

  JGI_INSTALL_BASEDIR: "/tmp"
  JGI_GLOBUS_EP: "45afb626-a4bd-11e8-96f0-0a6d4e044368"
  JGI_GLOBUS_ROOT_DIR: "/"
  JGI_GLOBUS_DEFAULT_DIR: "~"
  JGI_RMQ_HOST: "rmq.lbl.gov"
  JGI_RMQ_PORT: 5672
  JGI_PYTHON: "python"
  JGI_LOAD_PYTHON: "module load python"
  JGI_JAWS_GROUP: "jaws"
  JGI_JTM_GROUP: "jaws"
  JGI_CLIENT_GROUP: "jgi"
  JGI_JAWS_SCRATCH_BASEDIR: "/global/scratch/jaws"
  JGI_JTM_SCRATCH_BASEDIR: "/global/scratch/jaws"
  JGI_JAWS_SW_BASEDIR: "/global/home/groups-sw/lr_jgicloud"
  JGI_JTM_SW_BASEDIR: "/global/home/groups-sw/lr_jgicloud"
  JGI_REF_DATA_DIR: "/global/scratch/jaws/refdata"
  JGI_SUPERVISOR_HOST: "http://lrc-services.lbl.gov"
  JGI_CONTAINER_TYPE: "singularity"
  JGI_DB_HOST: "jaws-db.lbl.gov"
  JGI_DB_PORT: 3306
  JGI_CLUSTER_QOS: "condo_jgicloud"
  JGI_CLUSTER_PARTITION: "lr3"
  JGI_CLUSTER_ACCOUNT: "lr_jgicloud"
  JGI_CLUSTER_CONSTRAINT: ""
  JGI_MAX_RAM_GB: 1024
  JGI_LOAD_JAVA: "module load java"

  CASCADE_INSTALL_BASEDIR: "/tmp"
  CASCADE_GLOBUS_EP: "9d6d994a-6d04-11e5-ba46-22000b92c6ec"
  CASCADE_GLOBUS_ROOT_DIR: "/"
  CASCADE_GLOBUS_DEFAULT_DIR: "/"
  CASCADE_RMQ_HOST: "localhost"
  CASCADE_RMQ_PORT: 5672
  CASCADE_PYTHON: "python3.6"
  CASCADE_LOAD_PYTHON: ". /opt/rh/rh-python36/enable"
  CASCADE_JAWS_GROUP: "svc-jtm-manager"
  CASCADE_JTM_GROUP: "svc-jtm-user"
  CASCADE_CLIENT_GROUP: "svc-jtm-manager"
  CASCADE_JAWS_SCRATCH_BASEDIR: "/dtemp/mscjgi"
  CASCADE_JTM_SCRATCH_BASEDIR: "/dtemp/mscjgi"
  CASCADE_JAWS_SW_BASEDIR: "/dtemp/mscjgi"
  CASCADE_JTM_SW_BASEDIR: "/dtemp/mscjgi"
  CASCADE_REF_DATA_DIR: "/dtemp/mscjgi/refdata" # TODO: Needs to be rsync'd
  CASCADE_SUPERVISOR_HOST: "http://localhost"
  CASCADE_CONTAINER_TYPE: "singularity"
  CASCADE_DB_HOST: "localhost"
  CASCADE_DB_PORT: 3306
  CASCADE_CLUSTER_QOS: ""
  CASCADE_CLUSTER_PARTITION: ""
  CASCADE_CLUSTER_ACCOUNT: "mscjgi"
  CASCADE_CLUSTER_CONSTRAINT: ""
  CASCADE_MAX_RAM_GB: 1024  #TODO: Find a more accurate number
  CASCADE_LOAD_JAVA: ":"  # no-op

# this needs to be commented out in the jobs definitions, for the jobs to
# run in any case and not only when pushing a merge request.
.only-default: &only-default
  tags:
    - aws
    - jaws
  only:
    - master
    - branches
    - merge_requests
    - tags

test-rpc:
  <<: *only-default
  stage: unit-test
  script:
    - python3 -m venv test-venv
    - source test-venv/bin/activate
    - pip install -r rpc/requirements.txt
    - pip install flake8
    - pip install pytest
    - make test-rpc
test-site:
  <<: *only-default
  stage: unit-test
  script:
    - python3 -m venv test-venv
    - source test-venv/bin/activate
    - pip install rpc/
    - pip install -r site/requirements.txt
    - pip install flake8
    - pip install pytest
    - make test-site
test-central:
  <<: *only-default
  stage: unit-test
  script:
    - python3 -m venv test-venv
    - source test-venv/bin/activate
    - pip install rpc/
    - pip install -r central/requirements.txt
    - pip install flake8
    - pip install pytest
    - make test-central
test-client:
  <<: *only-default
  stage: unit-test
  script:
      # some unit tests for client require 'womtool' to be in the PATH
    - export PATH=/jaws-ci/bin:$PATH
    - python3 -m venv test-venv
    - source test-venv/bin/activate
    - pip install -r client/requirements.txt
    - pip install flake8
    - pip install pytest
    - make test-client
test-jtm:
  <<: *only-default
  stage: unit-test
  script:
    - python3 -m venv test-venv
    - source test-venv/bin/activate
    - pip install rpc/
    - pip install -r jtm/requirements.txt
    - pip install flake8
    - pip install pytest
    - make test-jtm
package:
  <<: *only-default
  stage: package
  script:
    - python3 -m venv pkg-venv
    - source pkg-venv/bin/activate
    - pip install wheel
    - make pkg
  artifacts:
    name: "packages-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
    expire_in: 6 hour
    paths:
      - rpc/dist
      - site/dist
      - client/dist
      - central/dist
      - jtm/dist

## integration tests - only run on merge request
deploy-jaws-central-dev:
  stage: deploy-jaws
  tags:
    - central
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CENTRAL"
    DEPLOY_JAWS_CLIENT: 1
  environment:
    name: "central/dev"
  script:
    - ./test/integration/deploy-central
  only:
  - dev
deploy-jaws-central-staging:
  stage: deploy-jaws
  tags:
    - central
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "CENTRAL"
    DEPLOY_JAWS_CLIENT: 0
  environment:
    name: "central/staging"
  script:
    - ./test/integration/deploy-central
  only:
  - staging
deploy-jaws-central-prod:
  stage: deploy-jaws
  tags:
    - central
  variables:
    DEPLOYMENT_NAME: "prod"
    JAWS_SITE: "CENTRAL"
    DEPLOY_JAWS_CLIENT: 0
  environment:
    name: "central/production"
  script:
    - ./test/integration/deploy-central
  only:
  - master

deploy-jaws-cori-dev:
  stage: deploy-jaws
  tags:
    - cori
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CORI"
    DEPLOY_JAWS_CLIENT: 1
  environment:
    name: "cori/dev"
  script:
    - ./test/integration/deploy-jaws
  only:
  - dev
deploy-jaws-cori-staging:
  stage: deploy-jaws
  tags:
    - cori
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "CORI"
    DEPLOY_JAWS_CLIENT: 1
  environment:
    name: "cori/staging"
  script:
    - ./test/integration/deploy-jaws
  only:
  - staging
deploy-jaws-cori-prod:
  stage: deploy-jaws
  tags:
    - cori
  variables:
    DEPLOYMENT_NAME: "prod"
    JAWS_SITE: "CORI"
    DEPLOY_JAWS_CLIENT: 1
  environment:
    name: "cori/production"
  script:
    - ./test/integration/deploy-jaws
  only:
  - master

deploy-jaws-jgi-dev:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "JGI"
    DEPLOY_JAWS_CLIENT: 1
  environment:
    name: "jgi/dev"
  script:
    - ./test/integration/deploy-jaws
  only:
  - dev
deploy-jaws-jgi-staging:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "JGI"
    DEPLOY_JAWS_CLIENT: 1
  environment:
    name: "jgi/staging"
  script:
    - ./test/integration/deploy-jaws
  only:
  - staging
deploy-jaws-jgi-prod:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    DEPLOYMENT_NAME: "prod"
    JAWS_SITE: "JGI"
    DEPLOY_JAWS_CLIENT: 1
  environment:
    name: "jgi/production"
  script:
    - ./test/integration/deploy-jaws
  only:
  - master

deploy-jaws-cascade-dev:
  stage: deploy-jaws
  tags:
    - cascade
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CASCADE"
  environment:
    name: "cascade/dev"
  script:
    - ./test/integration/deploy-jaws
