stages:
  - linter
  - test
  - reports
  - unit-test
  - image-build
  - deploy-jaws
  - package
  - release-jaws
  - end-to-end-test

include:
  - project: "advanced-analysis/ci-templates"
    ref: "main"
    file: "Code-Quality.gitlab-ci.yml"

variables:
  GIT_STRATEGY: clone

  JAWS_SITE_NAMES: "CORI JGI TAHOMA AWS ASSEMBLY NMDC PERLMUTTER DORI"
  JAWS_SITE_VERSION: "1.1.2"

# this needs to be commented out in the jobs definitions, for the jobs to
# run in any case and not only when pushing a merge request.
.shell-default: &shell-default
  tags:
    - shared-shell
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'

.docker-default: &docker-default
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags:
    - docker-build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
  coverage: '/(?i)TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

flake-rpc:
  <<: *shell-default
  stage: linter
  script:
    - flake8 --show-source --statistics rpc

flake-site:
  <<: *shell-default
  stage: linter
  script:
    - flake8 --show-source --statistics site

test-rpc:
  <<: *docker-default
  stage: unit-test
  script:
    - docker build -t jaws-site-rpc --target test-rpc .
    - docker run --rm -v $CI_PROJECT_DIR/rpc/coverage:/usr/app/rpc/coverage jaws-site-rpc
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: rpc/coverage/rpc.xml

test-site:
  <<: *docker-default
  stage: unit-test
  script:
    - docker build -t jaws-site --target test-site .
    - docker run --rm -v $CI_PROJECT_DIR/site/coverage:/usr/app/coverage jaws-site
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: site/coverage/site.xml

build-site:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags:
    - docker-build
  stage: image-build
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY_IMAGE:$JAWS_SITE_VERSION
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $GITLAB_IMAGE_TAG .
    - docker push $GITLAB_IMAGE_TAG
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"

.deploy-apptainer-template: &deploy-apptainer-template
  variables:
    CONTAINER_RUNTIME: "apptainer"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh

## integration tests - only run on merge request
deploy-jaws-aws-dev:
  stage: deploy-jaws
  tags:
    - aws-dev
  variables:
    JAWS_DEPLOYMENT_NAME: "dev"
    JAWS_SITE_NAME: "AWS"
  environment:
    name: "aws/dev"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_TAG == "dev"'

deploy-jaws-aws-prod:
  stage: release-jaws
  tags:
    - aws-prod
  variables:
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "AWS"
  environment:
    name: "aws/prod"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: manual

deploy-jaws-assembly-prod:
  stage: release-jaws
  tags:
    - assembly-prod
  variables:
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "ASSEMBLY"
  environment:
    name: "assembly/prod"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: manual

deploy-jaws-cori-dev:
  stage: deploy-jaws
  tags:
    - cori20
  variables:
    JAWS_DEPLOYMENT_NAME: "dev"
    JAWS_SITE_NAME: "CORI"
  environment:
    name: "cori/dev"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_TAG == "dev"'

deploy-jaws-cori-staging:
  stage: deploy-jaws
  tags:
    - cori20
  variables:
    JAWS_DEPLOYMENT_NAME: "staging"
    JAWS_SITE_NAME: "CORI"
  environment:
    name: "cori/staging"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  allow_failure: true

deploy-jaws-cori-prod:
  stage: release-jaws
  tags:
    - cori20
  variables:
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "CORI"
  environment:
    name: "cori/production"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: manual

deploy-jaws-jgi-dev:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    CONTAINER_RUNTIME: "apptainer"
    JAWS_DEPLOYMENT_NAME: "dev"
    JAWS_SITE_NAME: "JGI"
  environment:
    name: "jgi/dev"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_TAG == "dev"'

deploy-jaws-jgi-staging:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    JAWS_DEPLOYMENT_NAME: "staging"
    JAWS_SITE_NAME: "JGI"
    CONTAINER_RUNTIME: "apptainer"
  environment:
    name: "jgi/staging"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
  allow_failure: true

deploy-jaws-jgi-prod:
  stage: release-jaws
  tags:
    - jgi
  variables:
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "JGI"
    CONTAINER_RUNTIME: "apptainer"
  environment:
    name: "jgi/production"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      when: manual

deploy-jaws-tahoma-dev:
  stage: deploy-jaws
  tags:
    - tahoma
    - pnnl
  variables:
    no_proxy: "127.0.0.1, localhost, *.pnnl.gov *pnl.gov"
    HTTP_PROXY: "http://proxy.emsl.pnl.gov:3128"
    http_proxy: "http://proxy.emsl.pnl.gov:3128"
    HTTPS_PROXY: "http://proxy.emsl.pnl.gov:3128"
    https_proxy: "http://proxy.emsl.pnl.gov:3128"
    JAWS_DEPLOYMENT_NAME: "dev"
    JAWS_SITE_NAME: "TAHOMA"
    CONTAINER_RUNTIME: "apptainer"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_TAG == "dev"'

deploy-jaws-tahoma-staging:
  stage: deploy-jaws
  tags:
    - tahoma
    - pnnl
  variables:
    no_proxy: "127.0.0.1, localhost, *.pnnl.gov *pnl.gov"
    HTTP_PROXY: "http://proxy.emsl.pnl.gov:3128"
    http_proxy: "http://proxy.emsl.pnl.gov:3128"
    HTTPS_PROXY: "http://proxy.emsl.pnl.gov:3128"
    https_proxy: "http://proxy.emsl.pnl.gov:3128"
    JAWS_DEPLOYMENT_NAME: "staging"
    JAWS_SITE_NAME: "TAHOMA"
    CONTAINER_RUNTIME: "apptainer"
  environment:
    name: "tahoma/staging"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      allow_failure: true
  allow_failure: true

deploy-jaws-tahoma-prod:
  stage: release-jaws
  tags:
    - tahoma
    - pnnl
  variables:
    no_proxy: "127.0.0.1, localhost, *.pnnl.gov *pnl.gov"
    HTTP_PROXY: "http://proxy.emsl.pnl.gov:3128"
    http_proxy: "http://proxy.emsl.pnl.gov:3128"
    HTTPS_PROXY: "http://proxy.emsl.pnl.gov:3128"
    https_proxy: "http://proxy.emsl.pnl.gov:3128"
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "TAHOMA"
    CONTAINER_RUNTIME: "apptainer"
  environment:
    name: "tahoma/prod"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      when: manual

deploy-jaws-nmdc-dev:
  stage: deploy-jaws
  tags:
    - nmjaws
  variables:
    JAWS_DEPLOYMENT_NAME: "dev"
    JAWS_SITE_NAME: "NMDC"
  environment:
    name: "nmdc/dev"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_TAG == "dev"'

deploy-jaws-nmdc-staging:
  stage: deploy-jaws
  tags:
    - nmjaws
  variables:
    JAWS_DEPLOYMENT_NAME: "staging"
    JAWS_SITE_NAME: "NMDC"
  environment:
    name: "nmdc/staging"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
  allow_failure: true

deploy-jaws-nmdc-prod:
  stage: release-jaws
  tags:
    - nmjaws
  variables:
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "NMDC"
  environment:
    name: "nmdc/production"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: manual

deploy-jaws-perlmutter-dev:
  stage: deploy-jaws
  tags:
    - perlmutter
  variables:
    JAWS_DEPLOYMENT_NAME: "dev"
    JAWS_SITE_NAME: "PERLMUTTER"
  environment:
    name: "perlmutter/dev"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_TAG == "dev"'

deploy-jaws-perlmutter-staging:
  stage: deploy-jaws
  tags:
    - perlmutter
  variables:
    JAWS_DEPLOYMENT_NAME: "staging"
    JAWS_SITE_NAME: "PERLMUTTER"
  environment:
    name: "perlmutter/staging"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
  allow_failure: true

deploy-jaws-perlmutter-prod:
  stage: release-jaws
  tags:
    - perlmutter
  variables:
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "PERLMUTTER"
  environment:
    name: "perlmutter/production"
  script:
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: manual

deploy-jaws-dori-dev:
  stage: deploy-jaws
  tags:
    - dori
  variables:
    JAWS_DEPLOYMENT_NAME: "dev"
    JAWS_SITE_NAME: "DORI"
    CONTAINER_RUNTIME: "apptainer"
  environment:
    name: "dori/dev"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: '$CI_COMMIT_TAG == "dev"'

deploy-jaws-dori-staging:
  stage: deploy-jaws
  tags:
    - dori
  variables:
    JAWS_DEPLOYMENT_NAME: "staging"
    JAWS_SITE_NAME: "DORI"
    CONTAINER_RUNTIME: "apptainer"
  environment:
    name: "dori/staging"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  allow_failure: true

deploy-jaws-dori-prod:
  stage: release-jaws
  tags:
    - dori
  variables:
    JAWS_DEPLOYMENT_NAME: "prod"
    JAWS_SITE_NAME: "DORI"
    CONTAINER_RUNTIME: "apptainer"
  environment:
    name: "dori/production"
  script:
    - apptainer remote login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "docker://$CI_REGISTRY"
    - ./test/integration/deploy-jaws-site.sh
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: manual

cori-staging-test:
  stage: end-to-end-test
  variables:
    JAWS_DEPLOYMENT_NAME: "staging"
    JAWS_SITE_NAME: "cori"
    RUN_END_TO_END: "true"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  trigger:
    project: advanced-analysis/jaws-tests
    strategy: depend
  allow_failure: true
