stages:
  - test
  - unit-test
  - package
  - deploy-jaws
  - smoke-tests
  - deployment-tests
  - stress-tests
  - deploy-docs

include:
  - template: Security/SAST.gitlab-ci.yml

services:
  - docker:19.03.12-dind

variables:
  ## Configs for docker-executor
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

  GIT_STRATEGY: clone

  ## GLOBAL INSTALL VARIABLES:
  JAWS_SITES: "CORI JGI TAHOMA"
  JAWS_VERSION: "2.5.0"
  JAWS_DOCS_URL: "https://jaws-docs.readthedocs.io/en/latest/"
  JAWS_CENTRAL_HOST: "http://jaws.lbl.gov"
  JAWS_RMQ_HOST: "rmq.lbl.gov"
  JAWS_RMQ_PORT: 5672
  JAWS_GLOBUS_CLIENT_ID: "1a130a01-48bc-489b-a729-9ab858de1755"
  CROMWELL_VERSION: "58"
  CROMWELL_JAR_URL: "https://github.com/broadinstitute/cromwell/releases/download/58/cromwell-58.jar"
  WOMTOOL_JAR_URL: "https://github.com/broadinstitute/cromwell/releases/download/58/womtool-58.jar"
  JAWS_DB_HOST: "jaws-db.lbl.gov"
  JAWS_DB_PORT: 3306

  ## DEPLOYMENT-SPECIFIC VARIABLES:
  dev_LOG_LEVEL: "DEBUG"
  dev_JAWS_SUPERVISOR_PORT: 64101
  dev_JTM_SUPERVISOR_PORT: 64111
  dev_JAWS_CENTRAL_SUPERVISOR_PORT: 64121
  dev_JAWS_AUTH_PORT: 3001
  dev_JAWS_REST_PORT: 5001
  dev_CROMWELL_PORT: 50101
  staging_LOG_LEVEL: "DEBUG"
  staging_JAWS_SUPERVISOR_PORT: 64102
  staging_JTM_SUPERVISOR_PORT: 64112
  staging_JAWS_CENTRAL_SUPERVISOR_PORT: 64122
  staging_JAWS_AUTH_PORT: 3002
  staging_JAWS_REST_PORT: 5002
  staging_CROMWELL_PORT: 50102
  prod_LOG_LEVEL: "INFO"
  prod_JAWS_SUPERVISOR_PORT: 64103
  prod_JTM_SUPERVISOR_PORT: 64113
  prod_JAWS_CENTRAL_SUPERVISOR_PORT: 64123
  prod_JAWS_AUTH_PORT: 3003
  prod_JAWS_REST_PORT: 5003
  prod_CROMWELL_PORT: 50103

  ## CENTRAL-SPECIFIC VARIABLES:
  CENTRAL_INSTALL_BASEDIR: "/opt/jaws"
  CENTRAL_PYTHON: "python3"
  CENTRAL_LOAD_PYTHON: ""
  CENTRAL_JAWS_GROUP: "jaws"
  CENTRAL_JAWS_SCRATCH_BASEDIR: "/tmp/jaws-tmp"
  CENTRAL_SUPERVISOR_HOST: "http://jaws.lbl.gov"

  ## SITE-SPECIFIC VARIABLES:
  CORI_CLIENT_INSTALL_BASEDIR: "/global/cfs/projectdirs/jaws"
  CORI_INSTALL_BASEDIR: "/global/cfs/projectdirs/jaws/jaws-install"
  CORI_GLOBUS_EP: "be1ff650-dcbc-11ea-85a2-0e1702b77d41"
  CORI_GLOBUS_HOST_PATH: "/"
  CORI_PYTHON: "python3"
  CORI_LOAD_PYTHON: "module load python/3.8-anaconda-2020.11"
  CORI_JAWS_GROUP: "jaws"
  CORI_JTM_GROUP: "jaws_jtm"
  CORI_CLIENT_GROUP: "genome"
  CORI_JAWS_SCRATCH_BASEDIR: "/global/cscratch1/sd/jaws"
  CORI_JTM_SCRATCH_BASEDIR: "/global/cscratch1/sd/jaws_jtm"
  CORI_REF_DATA_DIR: "/global/dna/shared/databases/jaws/refdata"
  CORI_SUPERVISOR_HOST: "http://cori20.nersc.gov"
  CORI_CONTAINER_TYPE: "shifter"
  CORI_CONTAINER_TMPDIR: "/global/cscratch1/sd/jaws_jtm"
  CORI_CLUSTER_QOS: "genepool_special"
  CORI_CLUSTER_PARTITION: ""
  CORI_CLUSTER_ACCOUNT: "fungalp"
  CORI_CLUSTER_CONSTRAINT: "haswell"
  CORI_MAX_RAM_GB: 2048
  CORI_LOAD_JAVA: ""
  CORI_DATA_REPO_BASEDIR: "/global/cfs/projectdirs/jaws"
  CORI_RMQ_HOST: "rmq.lbl.gov"
  CORI_RMQ_PORT: 5672

  JGI_CLIENT_INSTALL_BASEDIR: "/global/home/groups-sw/lr_jgicloud"
  JGI_INSTALL_BASEDIR: "/global/home/groups-sw/lr_jgicloud/jaws-install"
  JGI_GLOBUS_EP: "e8b18c38-36cd-11eb-b54c-02d9497ca481"
  JGI_GLOBUS_HOST_PATH: "/global/scratch/jaws"
  JGI_PYTHON: "python"
  JGI_LOAD_PYTHON: "module load python/3.8.2-dll"
  JGI_JAWS_GROUP: "jaws"
  JGI_JTM_GROUP: "jaws"
  JGI_CLIENT_GROUP: "jgi"
  JGI_JAWS_SCRATCH_BASEDIR: "/global/scratch/jaws"
  JGI_JTM_SCRATCH_BASEDIR: "/global/scratch/jaws"
  JGI_REF_DATA_DIR: "/global/scratch/jaws/refdata"
  JGI_SUPERVISOR_HOST: "http://lrc-services.lbl.gov"
  JGI_CONTAINER_TYPE: "singularity"
  JGI_CONTAINER_TMPDIR: "/global/scratch/jaws"
  JGI_CLUSTER_QOS: "normal"
  JGI_CLUSTER_PARTITION: "jgi"
  JGI_CLUSTER_ACCOUNT: "jgi"
  JGI_CLUSTER_CONSTRAINT: ""
  JGI_MAX_RAM_GB: 250
  JGI_LOAD_JAVA: "module load java"
  JGI_DATA_REPO_BASEDIR: "/global/scratch/jaws"
  JGI_RMQ_HOST: "rmq.lbl.gov"
  JGI_RMQ_PORT: 5672

  TAHOMA_CLIENT_INSTALL_BASEDIR: "/tahoma/mscjgi/jaws-install/jaws-client/"
  TAHOMA_INSTALL_BASEDIR: "/tahoma/mscjgi/jaws-install"
  TAHOMA_GLOBUS_EP: "8e65719e-1a53-11ec-a09f-6b21ca6daf73"
  TAHOMA_GLOBUS_HOST_PATH: "/tahoma/mscjgi"
  TAHOMA_PYTHON: "python"
  TAHOMA_LOAD_PYTHON: "module load python/3.8.1"
  TAHOMA_JAWS_GROUP: "svc-jtm-manager"
  TAHOMA_JTM_GROUP: "svc-jtm-user"
  TAHOMA_CLIENT_GROUP: "svc-jtm-manager"
  TAHOMA_JAWS_SCRATCH_BASEDIR: "/tahoma/mscjgi"
  TAHOMA_JTM_SCRATCH_BASEDIR: "/tahoma/mscjgi"
  TAHOMA_REF_DATA_DIR: "/tahoma/mscjgi/refdata"
  TAHOMA_SUPERVISOR_HOST: "http://localhost"
  TAHOMA_CONTAINER_TYPE: "singularity"
  TAHOMA_CONTAINER_TMPDIR: "/big_scratch"
  TAHOMA_CLUSTER_QOS: ""
  TAHOMA_CLUSTER_PARTITION: ""
  TAHOMA_CLUSTER_ACCOUNT: "mscjgi"
  TAHOMA_CLUSTER_CONSTRAINT: ""
  TAHOMA_MAX_RAM_GB: 1024  #TODO: Find a more accurate number
  TAHOMA_LOAD_JAVA: ""
  TAHOMA_DATA_REPO_BASEDIR: "/tahoma/mscjgi"
  TAHOMA_RMQ_HOST: "mscjgi-rabbitmq.emsl.pnl.gov"
  TAHOMA_RMQ_PORT: 5672

# this needs to be commented out in the jobs definitions, for the jobs to
# run in any case and not only when pushing a merge request.
.only-default: &only-default
  tags:
    - shared-shell
  only:
    - master
    - branches
    - merge_requests
    - tags

test:
  tags:
    - docker-build
  stage: test

  script:
      - echo "Testing"

bandit-sast:
  tags:
    - docker-build

semgrep-sast:
  tags:
    - docker-build

test-rpc:
  <<: *only-default
  stage: unit-test
  script:
    - python3.8 -m venv test-venv
    - source test-venv/bin/activate
    - pip3.8 install -r rpc/requirements.txt
    - pip3.8 install flake8 pytest pytest-cov
    - make test-rpc
  artifacts:
    reports:
      cobertura: rpc/coverage.xml
test-site:
  <<: *only-default
  stage: unit-test
  script:
    - python3.8 -m venv test-venv
    - source test-venv/bin/activate
    - pip3.8 install rpc/
    - pip3.8 install -r site/requirements.txt
    - pip3.8 install flake8 pytest pytest-cov
    - make test-site
  artifacts:
    reports:
      cobertura: site/coverage.xml
test-central:
  <<: *only-default
  stage: unit-test
  script:
    - python3.8 -m venv test-venv
    - source test-venv/bin/activate
    - pip3.8 install rpc/
    - pip3.8 install -r central/requirements.txt
    - pip3.8 install flake8 pytest pytest-cov
    - make test-central
  artifacts:
    reports:
      cobertura: central/coverage.xml

test-client:
  <<: *only-default
  stage: unit-test
  script:
      # some unit tests for client require 'womtool' to be in the PATH
    - export PATH=/jaws-ci/bin:$PATH
    - python3.8 -m venv test-venv
    - source test-venv/bin/activate
    - pip3.8 install -r client/requirements.txt
    - pip3.8 install flake8 pytest pytest-cov
    - make test-client
  artifacts:
    reports:
      cobertura: client/coverage.xml
  allow_failure: true

test-jtm:
  <<: *only-default
  stage: unit-test
  script:
    - python3.8 -m venv test-venv
    - source test-venv/bin/activate
    - pip3.8 install rpc/
    - pip3.8 install -r jtm/requirements.txt
    - pip3.8 install flake8 pytest pytest-cov
    - make test-jtm
  artifacts:
    reports:
      cobertura: jtm/coverage.xml

package:
  <<: *only-default
  stage: package
  script:
    - python3.8 -m venv pkg-venv
    - source pkg-venv/bin/activate
    - pip3.8 install wheel
    - make pkg

## integration tests - only run on merge request
deploy-jaws-central-dev:
  stage: deploy-jaws
  tags:
    - central
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CENTRAL"
  environment:
    name: "central/dev"
  script:
    - ./test/integration/deploy-central
  only:
  - dev

deploy-jaws-central-staging:
  stage: deploy-jaws
  tags:
    - central
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "CENTRAL"
  environment:
    name: "central/staging"
  script:
    - ./test/integration/deploy-central
  only:
  - staging

deploy-jaws-central-prod:
  stage: deploy-jaws
  tags:
    - central
  variables:
    DEPLOYMENT_NAME: "prod"
    JAWS_SITE: "CENTRAL"
  environment:
    name: "central/production"
  script:
    - ./test/integration/deploy-central
  only:
  - master

deploy-jaws-cori-dev:
  stage: deploy-jaws
  tags:
    - cori
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CORI"
  environment:
    name: "cori/dev"
  script:
    - ./test/integration/deploy-jaws
  only:
  - dev

deploy-jaws-cori-staging:
  stage: deploy-jaws
  tags:
    - cori
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "CORI"
  environment:
    name: "cori/staging"
  script:
    - ./test/integration/deploy-jaws
  only:
  - staging

deploy-jaws-cori-prod:
  stage: deploy-jaws
  tags:
    - cori
  variables:
    DEPLOYMENT_NAME: "prod"
    JAWS_SITE: "CORI"
  environment:
    name: "cori/production"
  script:
    - ./test/integration/deploy-jaws
  only:
  - master

deploy-jaws-jgi-dev:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "JGI"
  environment:
    name: "jgi/dev"
  script:
    - ./test/integration/deploy-jaws
  only:
  - dev

deploy-jaws-jgi-staging:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "JGI"
  environment:
    name: "jgi/staging"
  script:
    - ./test/integration/deploy-jaws
  only:
  - staging

deploy-jaws-jgi-prod:
  stage: deploy-jaws
  tags:
    - jgi
  variables:
    DEPLOYMENT_NAME: "prod"
    JAWS_SITE: "JGI"
  environment:
    name: "jgi/production"
  script:
    - ./test/integration/deploy-jaws
  only:
  - master

deploy-jaws-tahoma-dev:
  stage: deploy-jaws
  tags:
    - tahoma
    - pnnl
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "TAHOMA"
  environment:
    name: "tahoma/dev"
  script:
    - ./test/integration/deploy-jaws
  only:
    - dev
  allow_failure: true

deploy-jaws-tahoma-staging:
  stage: deploy-jaws
  tags:
    - tahoma
    - pnnl
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "TAHOMA"
  environment:
    name: "tahoma/staging"
  script:
    - ./test/integration/deploy-jaws
  only:
    - staging
  allow_failure: true

deploy-jaws-tahoma-prod:
  stage: deploy-jaws
  tags:
    - tahoma
    - pnnl
  variables:
    DEPLOYMENT_NAME: "prod"
    JAWS_SITE: "TAHOMA"
  environment:
    name: "tahoma/prod"
  script:
    - ./test/integration/deploy-jaws
  only:
    - master
  allow_failure: true

cori-dev-smoke-tests:
  stage: smoke-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CORI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh smoke-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

jgi-dev-smoke-tests:
  stage: smoke-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "JGI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh smoke-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

tahoma-dev-smoke-tests:
  stage: smoke-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "TAHOMA"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh smoke-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

cori-dev-deployment-tests:
  stage: deployment-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CORI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh deployment-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

jgi-dev-deployment-tests:
  stage: deployment-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "JGI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh deployment-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

tahoma-dev-deployment-tests:
  stage: deployment-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "TAHOMA"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh deployment-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

cori-dev-stress-tests:
  stage: stress-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "CORI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh stress-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

jgi-dev-stress-tests:
  stage: stress-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "JGI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh stress-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

tahoma-dev-stress-tests:
  stage: stress-tests
  variables:
    DEPLOYMENT_NAME: "dev"
    JAWS_SITE: "TAHOMA"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh stress-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "staging" && $CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

cori-staging-smoke-tests:
  stage: smoke-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "CORI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh smoke-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

jgi-staging-smoke-tests:
  stage: smoke-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "JGI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh smoke-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

tahoma-staging-smoke-tests:
  stage: smoke-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "TAHOMA"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh smoke-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

cori-staging-deployment-tests:
  stage: deployment-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "CORI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh deployment-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

jgi-staging-deployment-tests:
  stage: deployment-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "JGI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh deployment-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

tahoma-staging-deployment-tests:
  stage: deployment-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "TAHOMA"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh deployment-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

cori-staging-stress-tests:
  stage: stress-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "CORI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh stress-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

jgi-staging-stress-tests:
  stage: stress-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "JGI"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh stress-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

tahoma-staging-stress-tests:
  stage: stress-tests
  variables:
    DEPLOYMENT_NAME: "staging"
    JAWS_SITE: "TAHOMA"
  tags:
    - cori
  script:
    - ./test/integration/end-to-end-tests/pytest_wrapper.sh stress-tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

deploy-jaws-docs:
  stage: deploy-docs
  tags:
    - cori
  script:
    - git clone git@gitlab.com:jfroula/jaws-docs.git
    - cp -r docs/sphinx/source/* jaws-docs/docs/source/
    - cd jaws-docs
    - git commit -a -m 'syncing docs' || echo "nothing to commit"
    - git push || echo "nothing to push"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
  allow_failure: true
