---

services:
    # site:
    #     image: site:${JAWS_VERSION:-2.6.0-dev}
    #     command:
    #         - "jaws-site"
    #         - "--config"
    #         - "/etc/config/jaws-site.conf"
    #         - "--log"
    #         - "/var/log/site-central/site-central.log"
    #         - "--log-level"
    #         - "DEBUG"
    #         - "central-rpc"
    #     depends_on:
    #         - db
    #         - rabbitmq
    #     volumes:
    #         - $DATA_HOME/configs/site-central/jaws-site.conf:/etc/config/jaws-site.conf
    #         - $DATA_HOME/logs/site-central:/var/log/site-central:rw
    #         - $DATA_HOME/local/uploads:/data/uploads
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_VHOST: jaws_dev
            RABBITMQ_DEFAULT_USER: jaws
            RABBITMQ_DEFAULT_PASS: jawstest
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - jaws_rabbitmq_data:/data/rabbitmq
            - ./tests:/app_tests
    rpc_server:
        build:
            context: .
            dockerfile: site/site.Dockerfile
        container_name: rpc_server
        command: ["jaws-site", "rpc-server"]
        depends_on:
            - rabbitmq
        volumes:
            - .:/code
    site:
        build:
            context: .
            dockerfile: site/site.Dockerfile
        container_name: site
        command: ["jaws-site", "-h"]
        volumes:
            - .:/code
volumes:
    jaws_rabbitmq_data:
        driver: local
