version: '3.1'

networks:
  jaws-tier:
    driver: bridge
services:
  central:
    image: jaws_central:2.5.0
    environment:
      VERSION: 2.5.0
      DEPLOYMENT_NAME: dev
      JAWS_DOCS_URL: https://jaws-docs.readthedocs.io/en/latest/
      JAWS_CENTRAL_DB_HOST: jaws_db
      JAWS_CENTRAL_DB_PORT: 3306
      JAWS_CENTRAL_DB_PW: jawstest
      JAWS_CENTRAL_RMQ_PW: jawstest
      JAWS_CENTRAL_RMQ_HOST: jaws_rabbitmq
      JAWS_CENTRAL_RMQ_PORT: 5672
      JAWS_GLOBUS_CLIENT_ID: 29a47d96-76b4-4f2b-a8bb-a4cb38ea17e3
      JAWS_AUTH_PORT: 3000
      JAWS_CLIENT_SECRET: TlLwcYHZF2c4b/KXPAk+R/PMwzmaF7exyAut/GQbNA=
      JAWS_REST_PORT: 5000
    depends_on:
      - jaws_db
      - jaws_rabbitmq
    networks:
      - jaws-tier
    expose:
      - 3000
      - 5000
    ports:
      - "5000:5000"
      - "3000:3000"
  jaws_db:
    image: jaws_mysql:2.5.0
    restart: always
    environment:
      MYSQL_USER: jaws
      MYSQL_PASSWORD: jawstest
      MYSQL_DATABASE: jaws_central_dev
      MYSQL_ROOT_PASSWORD: jawstest
    expose:
      - 3306
    networks:
      - jaws-tier
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/
  jaws_rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_VHOST: jaws_dev
      RABBITMQ_DEFAULT_USER: jaws
      RABBITMQ_DEFAULT_PASS: jawstest
    expose:
      - 15672
      - 5672
      - 5673
    networks:
      - jaws-tier
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5673:5673"

