
---

services:
    db:
        image: mariadb
        container_name: "jaws-mysql"
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
            interval: 3s
            retries: 5
            start_period: 30s
        environment:
            MARIADB_DATABASE: 'jaws'
            MARIADB_USER: 'admin'
            MARIADB_PASSWORD: 'root'
            MARIADB_ROOT_PASSWORD: 'root'
        volumes:
            - jaws_mysql_data:/var/lib/mysql
    cromwell:
        build:
            context: .
            dockerfile: cromwell.Dockerfile
        container_name: cromwell_server
        ports:
            - "8000:8080"
        volumes:
            - jaws_cromwell_data:/data/cromwell

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_VHOST: jaws_dev
            RABBITMQ_DEFAULT_USER: jaws
            RABBITMQ_DEFAULT_PASS: jawstest
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - jaws_rabbitmq_data:/data/rabbitmq
            - ./tests:/app_tests
    task_logger:
        build:
            context: .
            dockerfile: site.Dockerfile
        container_name: jaws_site
        restart: unless-stopped
        command:
            - "jaws-site"
            - "--config"
            - "/etc/config/jaws-site.conf"
            - "--log"
            - "/var/log/site-central/site-central.log"
            - "--log-level"
            - "DEBUG"
            - "-h"
        links:
            - "db:database"
            - "rabbitmq:rpc"
        command: ["npx", "exec", "nodemon", "--exec", "jaws-site", "task-logger"]
        depends_on:
            - rabbitmq
            - db
        volumes:
            - .:/code
    rpc_server:
        build:
            context: .
            dockerfile: site.Dockerfile
        container_name: jaws_site
        restart: unless-stopped
        command:
            - "jaws-site"
            - "--config"
            - "/etc/config/jaws-site.conf"
            - "--log"
            - "/var/log/site-central/site-central.log"
            - "--log-level"
            - "DEBUG"
            - "-h"
        links:
            - "db:database"
            - "rabbitmq:rpc"
        command: ["npx", "exec", "nodemon", "--exec", "jaws-site", "rpc-server"]
        depends_on:
            - rabbitmq
            - db
        volumes:
            - .:/code
    runs_daemon:
        build:
            context: .
            dockerfile: site.Dockerfile
        container_name: jaws_site
        restart: unless-stopped
        command:
            - "jaws-site"
            - "--config"
            - "/etc/config/jaws-site.conf"
            - "--log"
            - "/var/log/site-central/site-central.log"
            - "--log-level"
            - "DEBUG"
            - "-h"
        links:
            - "db:database"
            - "rabbitmq:rpc"
        command: ["npx", "exec", "nodemon", "--exec", "jaws-site", "runs"]
        depends_on:
            - rabbitmq
            - db
        volumes:
            - .:/code
volumes:
    jaws_mysql_data:
        driver: local
    jaws_cromwell_data:
        driver: local
    jaws_rabbitmq_data:
        driver: local
