version: '3.1'

networks:
  central-tier:
    driver: bridge
services:
  central:
    image: jaws_central:2.0
    environment:
      VERSION: 2.0
      DEPLOYMENT_NAME: dev
      JAWS_DOCS_URL: https://jaws-docs.readthedocs.io/en/latest/
      JAWS_CENTRAL_DB_HOST: central_db
      JAWS_CENTRAL_DB_PORT: 3306
      JAWS_CENTRAL_DB_PW: jawstest
      JAWS_CENTRAL_RMQ_PW: jawstest
      JAWS_CENTRAL_RMQ_HOST: central_rabbitmq
      JAWS_CENTRAL_RMQ_PORT: 5672
      JAWS_GLOBUS_CLIENT_ID: 29a47d96-76b4-4f2b-a8bb-a4cb38ea17e3
      JAWS_AUTH_PORT: 3001
      JAWS_REST_PORT: 5001
    depends_on:
      - central_db
      - central_rabbitmq
    networks:
      - central-tier
  central_db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: jaws
      MYSQL_PASSWORD: jawstest
      MYSQL_DATABASE: jaws_central_dev
      MYSQL_ROOT_PASSWORD: jawstest
    expose:
      - 3306
    networks:
      - central-tier
  central_rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_VHOST: jaws_dev
      RABBITMQ_DEFAULT_USER: jaws
      RABBITMQ_DEFAULT_PASS: jawstest
    expose:
      - 15672
      - 5672
      - 5673
    networks:
      - central-tier
  site_db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: jaws
      MYSQL_PASSWORD: jawstest
      MYSQL_DATABASE: jaws_sitea_dev
      MYSQL_DATABASE: jaws_cromwell_dev
      MYSQL_ROOT_PASSWORD: jawstest
    expose:
      - 3306
    networks:
      - central-tier
  site_rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_VHOST: jaws_dev
      RABBITMQ_DEFAULT_USER: jaws
      RABBITMQ_DEFAULT_PASS: jawstest
    expose:
      - 15672
      - 5672
      - 5673
    networks:
      - central-tier
  site:
    image: jaws_site:2.0
    environment:
      DB_HOST: site_db
      DB_PORT: 3306
      DB_PW: jawstest
      JAWS_SITE: sitea
      RMQ_PW: jawstest
      RMQ_HOST: site_rabbitmq
      RMQ_PORT: 5672
      DEPLOYMENT_NAME: dev
      JAWS_CENTRAL_RMQ_PW: jawstest
      JAWS_CENTRAL_RMQ_HOST: central_rabbitmq
      JAWS_CENTRAL_RMQ_PORT: 5672
      JAWS_GLOBUS_CLIENT_ID: 29a47d96-76b4-4f2b-a8bb-a4cb38ea17e3
      GLOBUS_EP: /
      GLOBUS_ROOT_DIR: /
      GLOBUS_DEFAULT_DIR: /
      UPLOADS_SUBDIR: /uploads
      DOWNLOADS_SUBDIR: /downloads
      CROMWELL_PORT: 50001
    depends_on:
      - site_rabbitmq
      - site_db
      - central_rabbitmq
    networks:
      - central-tier
  cromwell:
    image: jaws_cromwell:2.0
    environment:
      CROMWELL_PORT: 8001
      CROMWELL_WORKFLOW_LOGS_DIR: /tmp/
      SITE_DB_HOST: site_db
      SITE_DB_PORT: 3306
      SITE_DB_PW: jawstest
      JAWS_SITE: sitea
      DEPLOYMENT_NAME: dev
      JAVA_OPTS: -Xmx5g -Dconfig.file=/etc/cromwell.conf -Djava.io.tmpdir=/tmp/     
      CROMWELL_EXECUTIONS_DIR: /tmp/cromwell-executions
    depends_on:
      - site_db
    networks:
      - central-tier

