#!/usr/bin/env bash

[[ -z $JAWS_SUPERVISORD_PW ]] && { printf "Missing JAWS_SUPERVISORD_PW variable.\n"; exit 1; }

INSTALLDIR=${1:-/tmp/jaws-supervisor}
SHIMPATH=${2:-/tmp/jaws-supervisor/shims}
[[ -d $INSTALLDIR ]] || mkdir $INSTALLDIR
[[ -d $INSTALLDIR/bin ]] || mkdir $INSTALLDIR/bin
[[ -f $INSTALLDIR/venv/bin/activate ]] || python3 -m venv $INSTALLDIR/venv

source $INSTALLDIR/venv/bin/activate

function not_available() {
  command -v $1 >/dev/null 2>&1
}

not_available "supervisord" || pip install supervisor

function generate_shim() {
prog=$1
cat <<EOM > $INSTALLDIR/bin/$prog
#!/usr/bin/env bash

source $INSTALLDIR/venv/bin/activate

$prog \$@
EOM
chmod +x $INSTALLDIR/bin/$prog
}

generate_shim supervisord
generate_shim supervisorctl

sed "s|{{shimpath}}|$SHIMPATH|g; s|{{installpath}}|$INSTALLDIR|g; s/{{password}}/$JAWS_SUPERVISORD_PW/g;" test/integration/cori/supervisord-config-jtm > $INSTALLDIR/supervisord-jtm.conf
sed "s|{{shimpath}}|$SHIMPATH|g; s|{{installpath}}|$INSTALLDIR|g; s/{{password}}/$JAWS_SUPERVISORD_PW/g;" test/integration/cori/supervisord-config-jaws > $INSTALLDIR/supervisord-jaws.conf
