#!/bin/bash

## VALIDATE ENVS
[[ -z $INSTALL_DIR ]] && { printf "Missing INSTALL_DIR variable.\n"; exit 1; }
[[ -z $JAWS_GROUP ]] && { printf "Missing JAWS_GROUP variable.\n"; exit 1; }
[[ -z $JTM_GROUP ]] && { printf "Missing JTM_GROUP variable.\n"; exit 1; }
[[ -z $JTM_WORKER_INSTALL_DIR ]] && { printf "Missing JTM_WORKER_INSTALL_DIR variable.\n"; exit 1; }
[[ -z $CLIENT_INSTALL_DIR ]] && { printf "Missing CLIENT_INSTALL_DIR variable.\n"; exit 1; }
[[ -z $CLIENT_GROUP ]] && { printf "Missing CLIENT_GROUP variable.\n"; exit 1; }

## DEFINE PATHS
CONFIG_DIR="$INSTALL_DIR/configs"

## CREATE DIRS
test -d "$INSTALL_DIR" || mkdir "$INSTALL_DIR"
test -d "$CONFIG_DIR" || mkdir "$CONFIG_DIR"
chgrp $JTM_GROUP "$INSTALL_DIR"
chgrp $JTM_GROUP "$CONFIG_DIR"
chmod 770 "$INSTALL_DIR"
chmod 770 "$CONFIG_DIR"

## DELETE OLD VENVS
test -d "$INSTALL_DIR/site" && rm -rf "$INSTALL_DIR/site"
test -d "$INSTALL_DIR/central" && rm -rf "$INSTALL_DIR/central"
test -d "$INSTALL_DIR/jtm" && rm -rf "$INSTALL_DIR/jtm"
test -d "$CLIENT_INSTALL_DIR" && rm -rf "$CLIENT_INSTALL_DIR"
test -d "$JTM_WORKER_INSTALL_DIR" && rm -rf "$JTM_WORKER_INSTALL_DIR"

## MAKE VENVS
module load python
make pkg
python3 -m venv "$INSTALL_DIR/site" && . "$INSTALL_DIR/site/bin/activate" && pip install rpc/dist/* && pip install site/dist/* && deactivate
python3 -m venv "$INSTALL_DIR/central" && . "$INSTALL_DIR/central/bin/activate" && pip install rpc/dist/* && pip install central/dist/* && deactivate
python3 -m venv "$INSTALL_DIR/jtm" && . "$INSTALL_DIR/jtm/bin/activate" && pip install rpc/dist/* && pip install jtm/dist/* && deactivate
python3 -m venv "$JTM_WORKER_INSTALL_DIR" && . "$JTM_WORKER_INSTALL_DIR/bin/activate" && pip install rpc/dist/* && pip install jtm/dist/* && deactivate
python3 -m venv "$CLIENT_INSTALL_DIR" && . "$CLIENT_INSTALL_DIR/bin/activate" && pip install jtm/dist/* && deactivate

## PERMISSIONS
function fix_perms() {
    local DIR="$1"
    local GROUP=$2
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R $GROUP "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}

fix_perms "$INSTALL_DIR/site" $JAWS_GROUP
fix_perms "$INSTALL_DIR/central" $JAWS_GROUP
fix_perms "$INSTALL_DIR/jtm" $JTM_GROUP

## COPY CLIENT CONFIG
cp "$CONFIG_DIR/jaws-client.conf" "$CLIENT_INSTALL_DIR/"
cp "$CONFIG_DIR/jaws-user.conf" "$CLIENT_INSTALL_DIR/"
chmod 644 "$CLIENT_INSTALL_DIR/jaws-client.conf"
chmod 644 "$CLIENT_INSTALL_DIR/jaws-user.conf"

# NB: chgrp doesn't work for parallel FS from gitlab-runner, so that's done in the jtm-worker-deploy and jaws-client-deploy scripts created by generate-shims instead
#cp "$CONFIG_DIR/jaws-jtm.conf" "$JTM_WORKER_INSTALL_DIR/"
#chmod 600 "$JTM_WORKER_INSTALL_DIR/jaws-jtm.conf"
