ARG JAWS_VERSION
FROM jaws_rpc:${JAWS_VERSION}

RUN pip install wheel
COPY docker-entrypoint.sh bin/

WORKDIR app/
COPY jaws/site .
RUN python setup.py bdist_wheel && pip install dist/*

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["jaws-site --log /tmp/site-central-rpc.log --config /etc/jaws-site.conf --log-level DEBUG central-rpc"]
