version: "3.1"
services:
  mysql:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "jaws"
      MYSQL_PASSWORD: "jawstest"
      MYSQL_DATABASE: "jaws-workflows"
    volumes:
      - "./sql_tables:/docker-entrypoint-initdb.d"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "jaws"
      RABBITMQ_DEFAULT_PASS: "password"
  cromwell:
    image: "broadinstitute/cromwell:49-8a159cd-SNAP"
    command: ["server"]
    ports:
      - "8000:8000"
