#!/usr/bin/env bash

NAME=${1:-jaws}
INSTALL_DIR=${2:-/tmp/jaws}
JTM_WORKER_INSTALL_DIR=${3:-/tmp/jaws}
JTM_SCRATCH_DIR=${4:-/scratch/jtm}
CLIENT_INSTALL_DIR=${5:-/tmp/jaws}
CLIENT_GROUP=${6:-jawsusers}
REF_DATA_DIR=${7:-/scratch/jaws/ref_data}

SHIM_DIR="$INSTALL_DIR/shims/"

[[ -d $SHIM_DIR ]] || mkdir $SHIM_DIR

cat <<EOM > $SHIM_DIR/jaws-central-auth-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $INSTALL_DIR/logs/central-auth.log --config $INSTALL_DIR/configs/jaws-central.conf --log-level INFO auth
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rest-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $INSTALL_DIR/logs/central-rest.log --config $INSTALL_DIR/configs/jaws-central.conf --log-level INFO rest
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rpc-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $INSTALL_DIR/logs/central-rpc.log --config $INSTALL_DIR/configs/jaws-central.conf --log-level INFO rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-site-daemon-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $INSTALL_DIR/logs/site-daemon.log --config $INSTALL_DIR/configs/jaws-site.conf --log-level INFO daemon
EOM

cat <<EOM > $SHIM_DIR/jaws-site-central-rpc-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $INSTALL_DIR/logs/site-central-rpc.log --config $INSTALL_DIR/configs/jaws-site.conf --log-level INFO central-rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-site-jtm-rpc-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $INSTALL_DIR/logs/site-jtm-rpc.log --config $INSTALL_DIR/configs/jaws-site.conf --log-level INFO jtm-rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-jtm-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/jtm/bin/activate
export JTM_CONFIG_FILE=$INSTALL_DIR/configs/jaws-jtm.conf

#HACK: see .gitlab-ci.yml for the explanation of why that copy does not happen in the CI directly
mkdir $JTM_WORKER_INSTALL_DIR
chgrp jaws_jtm $JTM_WORKER_INSTALL_DIR
cp $INSTALL_DIR/configs/jaws-jtm.conf $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
chgrp jaws_jtm $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
chmod 640 $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf

exec jtm --config=$INSTALL_DIR/configs/jaws-jtm.conf --debug manager -ld $INSTALL_DIR/logs/jtm
EOM

cat <<EOM > $SHIM_DIR/jaws-cromwell-$NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

# cromwell needs jtm-worker in it's \$PATH
source $INSTALL_DIR/jtm/bin/activate

# cromwell write cromwell-executions dir in cwd
cd $JTM_SCRATCH_DIR
exec java -Xmx5g -Dconfig.file="$INSTALL_DIR/configs/cromwell.conf" -Djava.io.tmpdir="\$TMPDIR" -jar "$INSTALL_DIR/cromwell.jar" server
EOM

cat <<EOM > $JTM_WORKER_INSTALL_DIR/shifter_exec.sh
#!/bin/bash
shifter --image=$1 -V $REF_DATA_DIR:/refdata $2 $3
EOM

chmod +x $SHIM_DIR/*
