#!/usr/bin/env bash

INSTALLDIR=${1:-/tmp/jaws-dev}
JTM_WORKER_INSTALL_DIR=${2:-/tmp/jaws-dev}
CLIENT_INSTALL_DIR=${3:-/tmp/jaws-dev}
CLIENTGROUP=${4:-jawsusers}
SHIMDIR="$INSTALLDIR/shims/"
CROMWELL_DIR=/global/cfs/projectdirs/jaws/cromwell

[[ -d $SHIMDIR ]] || mkdir $SHIMDIR

cat <<EOM > $SHIMDIR/jaws-central-auth-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALLDIR/central/bin/activate
exec jaws-central --log $INSTALLDIR/logs/central-auth.log --config $INSTALLDIR/configs/jaws-central.conf --log-level DEBUG auth
EOM

cat <<EOM > $SHIMDIR/jaws-central-rest-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALLDIR/central/bin/activate
exec jaws-central --log $INSTALLDIR/logs/central-rest.log --config $INSTALLDIR/configs/jaws-central.conf --log-level DEBUG rest
EOM

cat <<EOM > $SHIMDIR/jaws-central-rpc-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALLDIR/central/bin/activate
exec jaws-central --log $INSTALLDIR/logs/central-rpc.log --config $INSTALLDIR/configs/jaws-central.conf --log-level DEBUG rpc
EOM

cat <<EOM > $SHIMDIR/jaws-site-daemon-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

#HACK: see .gitlab-ci.yml for the explanation of why that copy does not happen in the CI directly
mkdir $CLIENT_INSTALL_DIR
chgrp genome $CLIENT_INSTALL_DIR
chmod 755 $CLIENT_INSTALL_DIR
cp $INSTALLDIR/configs/jaws-user.conf $CLIENT_INSTALL_DIR/jaws-user.conf
cp $INSTALLDIR/configs/jaws.conf $CLIENT_INSTALL_DIR/jaws.conf
chgrp genome $CLIENT_INSTALL_DIR/jaws-user.conf
chgrp genome $CLIENT_INSTALL_DIR/jaws.conf
chmod 644 $CLIENT_INSTALL_DIR/jaws-user.conf
chmod 644 $CLIENT_INSTALL_DIR/jaws.conf

chmod -R a+rX $CLIENT_INSTALL_DIR
chmod -R ug+rwX $CLIENT_INSTALL_DIR
chgrp -R $CLIENTGROUP $CLIENT_INSTALL_DIR
find $CLIENT_INSTALL_DIR -type d -exec /bin/chmod g+s '{}' \;

source $INSTALLDIR/site/bin/activate
exec jaws-site --log $INSTALLDIR/logs/site-daemon.log --config $INSTALLDIR/configs/jaws-site.conf --log-level DEBUG daemon
EOM

cat <<EOM > $SHIMDIR/jaws-site-central-rpc-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALLDIR/site/bin/activate
exec jaws-site --log $INSTALLDIR/logs/site-central-rpc.log --config $INSTALLDIR/configs/jaws-site.conf --log-level DEBUG central-rpc
EOM

cat <<EOM > $SHIMDIR/jaws-site-jtm-rpc-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALLDIR/site/bin/activate
exec jaws-site --log $INSTALLDIR/logs/site-jtm-rpc.log --config $INSTALLDIR/configs/jaws-site.conf --log-level DEBUG jtm-rpc
EOM

cat <<EOM > $SHIMDIR/jaws-jtm-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALLDIR/jtm/bin/activate
export JTM_CONFIG_FILE=$INSTALLDIR/configs/jaws-jtm.conf

#HACK: see .gitlab-ci.yml for the explanation of why that copy does not happen in the CI directly
mkdir $JTM_WORKER_INSTALL_DIR
chgrp jaws_jtm $JTM_WORKER_INSTALL_DIR
cp $INSTALLDIR/configs/jaws-jtm.conf $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
chgrp jaws_jtm $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
chmod 640 $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf

exec jtm --config=$INSTALLDIR/configs/jaws-jtm.conf --debug manager -ld $INSTALLDIR/logs/jtm
EOM

cat <<EOM > $SHIMDIR/jaws-cromwell-dev
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

# cromwell needs jtm to be in path
source $INSTALLDIR/jtm/bin/activate

cd /global/cscratch1/sd/jaws_jtm/dev/
exec java -Xmx5g -Dconfig.file="$INSTALLDIR/configs/cromwell.conf" -Djava.io.tmpdir="\$TMPDIR" -jar "$INSTALLDIR/cromwell.jar" server
EOM

cat <<EOM > $CROMWELL_DIR/shifter_exec.sh
#!/bin/bash
shifter --image=$1 -V /global/dna/shared/rqc/ref_databases:/refdata $2 $3
EOM

chmod +x $SHIMDIR/*
