#!/usr/bin/env bash

## DEFINE INSTALL VARS
DEPLOYMENT_NAME={{deployment_name}}
INSTALL_DIR={{site.local.install_dir}}
CONFIG_DIR=$INSTALL_DIR/config
SHIM_DIR=$INSTALL_DIR/shims
LOGS_DIR=$INSTALL_DIR/logs
JTM_WORKER_INSTALL_DIR={{site.local.jtm.worker_install_dir}}
CLIENT_INSTALL_DIR={{client.install_dir}
JAWS_GROUP={{site.local.group_perms.jaws}}
JTM_GROUP={{site.local.group_perms.jtm}}
REF_DATA_DIR={{site.local.ref_data_dir}}
LOG_LEVEL="DEBUG"

## VALIDATE ENVS
#[[ -z $DEPLOYMENT_NAME ]]          && { printf "Missing DEPLOYMENT_NAME variable.\n"; exit 1; }
#[[ -z $INSTALL_DIR ]]              && { printf "Missing INSTALL_DIR variable.\n"; exit 1; }
#[[ -z $CONFIG_DIR ]]               && { printf "Missing CONFIG_DIR variable.\n"; exit 1; }
#[[ -z $SHIM_DIR ]]                 && { printf "Missing SHIM_DIR variable.\n"; exit 1; }
#[[ -z $LOGS_DIR ]]                 && { printf "Missing LOGS_DIR variable.\n"; exit 1; }
#[[ -z $JTM_WORKER_INSTALL_DIR ]]   && { printf "Missing JTM_WORKER_INSTALL_DIR variable.\n"; exit 1; }
#[[ -z $CLIENT_INSTALL_DIR ]]       && { printf "Missing CLIENT_INSTALL_DIR variable.\n"; exit 1; }
#[[ -z $JTM_GROUP ]]                && { printf "Missing JTM_GROUP variable.\n"; exit 1; }
#[[ -z $CLIENT_GROUP ]]             && { printf "Missing CLIENT_GROUP variable.\n"; exit 1; }
#[[ -z $JAWS_GROUP ]]               && { printf "Missing JAWS_GROUP variable.\n"; exit 1; }
#[[ -z $REF_DATA_DIR ]]             && { printf "Missing REF_DATA_DIR variable.\n"; exit 1; }
#[[ -z $LOG_LEVEL ]]                && { printf "Missing LOG_LEVEL variable.\n"; exit 1; }

## CREATE DIRS
test -d $INSTALL_DIR || mkdir $INSTALL_DIR
test -d $SHIM_DIR || mkdir $SHIM_DIR
test -d $LOGS_DIR || mkdir $LOGS_DIR
test -d "$LOGS_DIR/jtm" || mkdir "$LOGS_DIR/jtm"
test -d $JTM_WORKER_INSTALL_DIR || mkdir $JTM_WORKER_INSTALL_DIR
chgrp $JTM_GROUP $INSTALL_DIR
chgrp $JTM_GROUP $SHIM_DIR
chgrp $JTM_GROUP $LOGS_DIR
chgrp $JTM_GROUP "$LOGS_DIR/jtm"
# chgrp doesn't work with parallel fs; see .gitlab-ci.yml for more info
#chgrp $JTM_GROUP $JTM_WORKER_INSTALL_DIR
chmod 770 $INSTALL_DIR
chmod 770 $SHIM_DIR
chmod 770 $LOGS_DIR
chmod 770 "$LOGS_DIR/jtm"
chmod 770 $JTM_WORKER_INSTALL_DIR

## WRITE SHIM SCRIPTS
cat <<EOM > $SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-auth.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL auth
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rest.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rest
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rpc-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rpc.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-site-daemon-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $LOGS_DIR/site-daemon.log --config $CONFIG_DIR/jaws-site.conf --log-level $LOG_LEVEL daemon
EOM

cat <<EOM > $SHIM_DIR/jaws-site-central-rpc-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $LOGS_DIR/site-central-rpc.log --config $CONFIG_DIR/jaws-site.conf --log-level $LOG_LEVEL central-rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-site-jtm-rpc-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $LOGS_DIR/site-jtm-rpc.log --config $CONFIG_DIR/jaws-site.conf --log-level DEBUG jtm-rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-jtm-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/jtm/bin/activate
export JTM_CONFIG_FILE=$CONFIG_DIR/jaws-jtm.conf

exec jtm --config=$CONFIG_DIR/jaws-jtm.conf --debug manager -ld $LOGS_DIR/jtm
EOM

cat <<EOM > $SHIM_DIR/jaws-cromwell-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

# cromwell needs jtm to be in path
source $INSTALL_DIR/jtm/bin/activate

cd $JTM_WORKER_INSTALL_DIR
exec java -Xmx5g -Dconfig.file="$CONFIG_DIR/cromwell.conf" -Djava.io.tmpdir="\$TMPDIR" -jar "$INSTALL_DIR/cromwell.jar" server
EOM

cat <<EOM > $JTM_WORKER_INSTALL_DIR/shifter_exec.sh
#!/usr/bin/env bash
shifter --image=$1 -V $REF_DATA_DIR:/refdata $2 $3
EOM

cat <<EOM > $SHIM_DIR/jaws-deploy-worker-$DEPLOYMENT_NAME
#!/usr/bin/env bash

# HACK: see .gitlab-ci.yml for the explanation of why that copy does not happen in the CI directly

test -d $JTM_WORKER_INSTALL_DIR || mkdir $JTM_WORKER_INSTALL_DIR
test -d $JTM_WORKER_INSTALL_DIR/staging || mkdir $JTM_WORKER_INSTALL_DIR/staging

cp $CONFIG_DIR/jaws-jtm.conf $JTM_WORKER_INSTALL_DIR/
chgrp $JTM_GROUP $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
chmod 770 $JTM_WORKER_INSTALL_DIR
chmod 777 $JTM_WORKER_INSTALL_DIR/staging
chmod 640 $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
EOM

cat <<EOM > $SHIM_DIR/jaws.sh
#!/usr/bin/env bash

source $CLIENT_INSTALL_DIR/bin/activate
export JAWS_CLIENT_CONFIG="$CLIENT_INSTALL_DIR/jaws-client.conf"
export JAWS_USER_CONFIG=~/jaws.conf
echo "Activated JAWS-$DEPLOYMENT_NAME; use 'deactivate' to exit."
EOM

cat <<EOM > $SHIM_DIR/jaws-deploy-client-$DEPLOYMENT_NAME
#!/usr/bin/env bash

# HACK: see .gitlab-ci.yml for the explanation of why that copy does not happen in the CI directly

test -d $CLIENT_INSTALL_DIR || mkdir $CLIENT_INSTALL_DIR
cp $CONFIG_DIR/jaws-client.conf $CLIENT_INSTALL_DIR/
cp $CONFIG_DIR/jaws.conf $CLIENT_INSTALL_DIR/
cp $SHIM_DIR/jaws.sh $CLIENT_INSTALL_DIR/

chmod -R ag+rX $CLIENT_INSTALL_DIR
chgrp -R $CLIENT_GROUP
find $CLIENT_INSTALL_DIR -type d -exec chmod g+s '{}' \;
EOM


## SET PERMISSIONS
chgrp $JTM_GROUP $SHIM_DIR/jaws-cromwell-$DEPLOYMENT_NAME
chgrp $JTM_GROUP $SHIM_DIR/jaws-jtm-$DEPLOYMENT_NAME
chgrp $JTM_GROUP $SHIM_DIR/jaws-deploy-worker-$DEPLOYMENT_NAME
chmod +x $SHIM_DIR/*
