#!/bin/bash -l
#SBATCH --mem=45G
#SBATCH --cpus-per-task 32
#SBATCH --time=72:00:00
#SBATCH --job-name=jaws_condor_small_worker
#SBATCH --partition=lr3
#SBATCH --qos=normal
#SBATCH --account=jgi
#SBATCH --nodes=1
#SBATCH -e /global/scratch/users/jaws/condor/worker_log/slurm/%N-%j.err
#SBATCH -o /global/scratch/users/jaws/condor/worker_log/slurm/%N-%j.out
#SBATCH --exclusive

srun -k -K0 /global/home/groups-sw/lr_jgicloud/condor/start_condor_worker.sh
# 72hr - 2min
sleep 259080
srun -k -K0 /global/home/groups-sw/lr_jgicloud/condor/stop_worker.sh
exit
