#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=12:00:00
#SBATCH --output=/global/cfs/projectdirs/m3408/aim2/metagenome/ReadbasedAnalysis/ReadbasedAnalysis.log
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --cpus-per-task 32
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=your@email
#SBATCH --constraint=haswell
#SBATCH --account=m3408
#SBATCH --job-name=ReadbasedAnalysis

cd /global/cfs/projectdirs/m3408/aim2/metagenome/ReadbasedAnalysis

java -Dconfig.file=ReadbasedAnalysis_cromwell.conf \
     -jar /global/common/software/m3408/cromwell-45.jar \
     run \
     -i ReadbasedAnalysis_inputs.json \
     -m cromwell_metadata.json \
     ReadbasedAnalysis.wdl
