#!/bin/bash

{% set sitename = "{}".format(install.components.jaws_site.site_name) -%}

set -eo pipefail

## DEFINE INSTALL VARS
group_perms={{client.group_perms}}
src_dir={{install.meta.src_dir}}
install_dir={{site[sitename]['install_dir']}}
client_dir={{client.install_dir}}
staging_user_dir={{client.staging_dir}}
data_repo_dir={{client.data_repo_basedir}}
shared_endpoint_group={{client.shared_endpoint_group}}
developer_mode={{install.meta.developer_mode}}

## PERMISSIONS
function fix_perms() {
    local dir=$1
    local group=$2
    chmod -R a+rX $dir
    chmod -R ug+rwX $dir
    [[ ! -z $group ]] && chgrp -R $group $dir
    if [[ -d $dir ]]; then
        find $dir -type d -exec chmod g+s '{}' \;
    fi
}

function setup_dir {
  local DIR="$1"
  local GROUP="$2"
  local PERMS="$3"
  [[ -z $DIR ]] && echo "missing DIR" && exit 1
  [[ -z $GROUP ]] && echo "missing GROUP" && exit 1
  echo "... $DIR"
  test -d "$DIR" || (mkdir -p "$DIR" && \
    chgrp "$GROUP" "$DIR" && \
    chmod "$PERMS" "$DIR")
}


## MAKE DIR IF NOT EXIST
test -d $client_dir && rm -rf $client_dir && mkdir $client_dir


## CREATE PYTHON VIRTUALENV
python3 -m venv $client_dir && \
  source $client_dir/bin/activate && \
  pip install --upgrade pip && \
  pip install wheel && \
  deactivate


## INSTALL JAWS FILES
if [[ $developer_mode == 1 ]]; then
  source $client_dir/bin/activate && \
    cd $src_dir/client && pip install -e . && \
    deactivate
else
  [[ -d $src_dir/client/dist ]] && rm -f $src_dir/client/dist/*
  cd $src_dir/client && python3 setup.py bdist_wheel
  source $client_dir/bin/activate && \
    pip install $src_dir/client/dist/* && \
    deactivate
  fix_perms $client_dir $group_perms
fi


## SETUP STAGING AND DATA REPO DIRS
if [[ ! -z $staging_user_dir ]]; then
    setup_dir "$staging_user_dir" "$shared_endpoint_group" 2775
fi
if [[ ! -z $data_repo_dir ]]; then
    setup_dir "$data_repo_dir" "$shared_endpoint_group" 2775
fi
