#!/bin/bash

{% set sitename = "{}".format(install.components.jaws_site.site_name) -%}

set -eo pipefail

## DEFINE INSTALL VARS
group_perms={{client.group_perms}}
src_dir={{install.meta.src_dir}}
install_dir={{site[sitename]['install_dir']}}
client_dir={{client.install_dir}}
developer_mode={{install.meta.developer_mode}}

## PERMISSIONS
function fix_perms() {
    local dir=$1
    local group=$2
    chmod -R a+rX $dir
    chmod -R ug+rwX $dir
    [[ ! -z $group ]] && chgrp -R $group $dir
    if [[ -d $dir ]]; then
        find $dir -type d -exec chmod g+s '{}' \;
    fi
}


## MAKE DIR IF NOT EXIST
test -d $client_dir && rm -rf $client_dir && mkdir $client_dir


## CREATE PYTHON VIRTUALENV
python3 -m venv $client_dir && \
  source $client_dir/bin/activate && \
  pip install --upgrade pip && \
  pip install wheel && \
  deactivate


# INSTALL JAWS FILES
if [[ $developer_mode == 1 ]]; then
  source $client_dir/bin/activate && \
    cd $src_dir/client && pip install -e . && \
    deactivate
else
  [[ -d $src_dir/client/dist ]] && rm -f $src_dir/client/dist/*
  cd $src_dir/client && python3 setup.py bdist_wheel
  source $client_dir/bin/activate && \
    pip install $src_dir/client/dist/* && \
    deactivate
fi

fix_perms $client_dir $group_perms
