swagger: "2.0"

info:
  title: JAWS OAuth2 server
  description: JAWS Authentication service
  version: "1.0"

paths:

  /tokeninfo:
    get:
      summary: OAuth2 token info
      operationId: jaws_auth.auth.get_tokeninfo
      consumes:
        - multipart/form-data
      responses:
        200:
          description: Token info object
          schema:
            type: object
            properties:
              uid:
                type: string
              scope:
                type: array
                items:
                  type: string
