#!/usr/bin/env bash

## DEFINE INSTALL VARS
INSTALL_DIR={{site.local.install_dir}}
JAWS_SCRATCH_DIR={{site.local.scratch_dir}}
JTM_SCRATCH_DIR={{site.local.jtm.scratch_dir}}
DEPLOY_JAWS_CLIENT={{site.local.deploy.client}}
JTM_WORKER_INSTALL_DIR={{site.local.jtm.worker_install_dir}}
CLIENT_INSTALL_DIR={{client.install_dir}}
JAWS_GROUP="{{site.local.group_perms.jaws}}"
JTM_GROUP="{{site.local.group_perms.jtm}}"
CLIENT_GROUP="{{site.local.group_perms.client}}"
REF_DATA_DIR={{site.local.ref_data_dir}}
UPLOADS_DIR=$JAWS_SCRATCH_DIR/uploads
DOWNLOADS_DIR=$JAWS_SCRATCH_DIR/downloads
CONFIG_DIR=$INSTALL_DIR/config
SHIM_DIR=$INSTALL_DIR/shims
LOGS_DIR=$INSTALL_DIR/logs
LOG_LEVEL="DEBUG"

printf "END deploy-jaws\n\n"

## MAKE DIR IF NOT EXIST
test -d "$SHIM_DIR" && rm -rf "$SHIM_DIR"
mkdir "$SHIM_DIR"
test -d "$LOGS_DIR" || mkdir "$LOGS_DIR"

## WRITE SHIM SCRIPTS

# If the DEPLOY-CLIENT flag is set, the deploy-client script will be run, but the files must have group and permissions set.
# Unfortunately, chgrp/chmod don't work on the parallel-fs when executed by the gitlab-runner for some reason; the
# solution is to have the jaws user perform these commands in one of the shims (under supervsiord), so it's executed before one
# of the required services is executed.  This is a hack.
FIX_PERMS_CLIENT=""
[[ -n "$DEPLOY_JAWS_CLIENT" ]] && [[ "$DEPLOY_JAWS_CLIENT" -eq 1 ]] && FIX_PERMS_CLIENT="fix_perms $CLIENT_GROUP $CLIENT_INSTALL_DIR"

cat <<EOM > $SHIM_DIR/jaws-site-daemon
#!/usr/bin/env bash

function fix_perms() {
    local GROUP="\$1"
    local DIR="\$2"
    chmod -R a+rX "\$DIR"
    chmod -R ug+rwX "\$DIR"
    chgrp -R "\$GROUP" "\$DIR"
    find "\$DIR" -type d -exec chmod g+s '{}' \;
}

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

test -d "$JAWS_SCRATCH_DIR" || mkdir "$JAWS_SCRATCH_DIR"
chmod 775 "$JAWS_SCRATCH_DIR"
test -d "$DOWNLOADS_DIR" || mkdir "$DOWNLOADS_DIR"
chmod 775 "$DOWNLOADS_DIR"

$FIX_PERMS_CLIENT

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $LOGS_DIR/site-daemon.log --config $CONFIG_DIR/jaws-site.conf --log-level $LOG_LEVEL daemon
EOM

cat <<EOM > $SHIM_DIR/jaws-site-central-rpc
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

# START RPC SERVER
source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $LOGS_DIR/site-central-rpc.log --config $CONFIG_DIR/jaws-site.conf --log-level $LOG_LEVEL central-rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-site-jtm-rpc
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/site/bin/activate
exec jaws-site --log $LOGS_DIR/site-jtm-rpc.log --config $CONFIG_DIR/jaws-site.conf --log-level DEBUG jtm-rpc
EOM

cat <<EOM > $SHIM_DIR/jaws-jtm
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8


# DEPLOY TO NFS DIR
# HACK: see .gitlab-ci.yml for the explanation of why that copy does not happen in the CI directly

test -d $JTM_WORKER_INSTALL_DIR || mkdir $JTM_WORKER_INSTALL_DIR
test -d $JTM_SCRATCH_DIR || mkdir $JTM_SCRATCH_DIR
test -d $UPLOADS_DIR || mkdir $UPLOADS_DIR

cp $CONFIG_DIR/jaws-jtm.conf $JTM_WORKER_INSTALL_DIR/
chgrp $JTM_GROUP $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
chgrp $JTM_GROUP $UPLOADS_DIR
chmod 770 $JTM_WORKER_INSTALL_DIR
chmod 640 $JTM_WORKER_INSTALL_DIR/jaws-jtm.conf
chmod 775 $JTM_SCRATCH_DIR
chmod 777 $UPLOADS_DIR


# RUN JTM

source $INSTALL_DIR/jtm/bin/activate
export JTM_CONFIG_FILE=$CONFIG_DIR/jaws-jtm.conf

exec jtm --config=$CONFIG_DIR/jaws-jtm.conf --debug manager -ld $LOGS_DIR
EOM

cat <<EOM > $SHIM_DIR/jaws-central-auth
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-auth.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL auth
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rest
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rest.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rest
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rpc
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rpc.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rpc
EOM


## SET PERMISSIONS
chgrp "$JTM_GROUP" $SHIM_DIR/jaws-jtm
chmod +x "$SHIM_DIR"/*
chgrp "$JAWS_GROUP" "$SHIM_DIR/jaws-central-auth"
chgrp "$JAWS_GROUP" "$SHIM_DIR/jaws-central-rest"
chmod 770 "$SHIM_DIR/jaws-central-auth"
chmod 770 "$SHIM_DIR/jaws-central-rest"

printf "END generate-shims\n\n"
