#!/usr/bin/env bash

## DEFINE INSTALL VAR
INSTALL_DIR={{site.local.install_dir}}
JAWS_GROUP={{site.local.group_perms.jaws}}
JTM_GROUP={{site.local.group_perms.jtm}}
JAWS_SUPERVISORD_PW={{site.local.supervisord.deploy_name.password}}
JAWS_SUPERVISOR_PORT={{site.local.supervisord.deploy_name.jaws_port}}
JTM_SUPERVISOR_PORT={{site.local.supervisord.deploy_name.jtm_port}}
SUPERVISOR_DIR={{site.local.supervisord.deploy_name.install_dir}}
SHIM_DIR=$INSTALL_DIR/shims
DEPLOY_DIR=$INSTALL_DIR/deploy


## CREATE DIRS
test -d $SUPERVISOR_DIR || mkdir $SUPERVISOR_DIR
test -d $INSTALL_DIR || mkdir $INSTALL_DIR
test -d $SHIM_DIR || mkdir $SHIM_DIR
chgrp $JTM_GROUP $SUPERVISOR_DIR
chgrp $JTM_GROUP $INSTALL_DIR
chgrp $JTM_GROUP $SHIM_DIR
chgrp $JTM_GROUP $LOG_DIR
chmod 770 $SUPERVISOR_DIR
chmod 770 $INSTALL_DIR
chmod 770 $SHIM_DIR

[[ -d $SUPERVISOR_DIR/bin ]] || mkdir $SUPERVISOR_DIR/bin
[[ -f $SUPERVISOR_DIR/venv/bin/activate ]] || python3 -m venv $SUPERVISOR_DIR/venv
chgrp -R $JTM_GROUP $SUPERVISOR_DIR/{bin,venv}

source $SUPERVISOR_DIR/venv/bin/activate

function not_available() {
  command -v $1 >/dev/null 2>&1
}

not_available "supervisord" || pip install supervisor

function generate_shim() {
prog=$1
cat <<EOM > $SUPERVISOR_DIR/bin/$prog
#!/usr/bin/env bash

source $SUPERVISOR_DIR/venv/bin/activate

$prog \$@
EOM
chmod +x $SUPERVISOR_DIR/bin/$prog
}

generate_shim supervisord
generate_shim supervisorctl

function fix_perms() {
    local DIR="$1"
    local GROUP=$2
    chmod -R 770 "$DIR"
    chgrp -R $GROUP "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}

fix_perms "$SUPERVISOR_DIR" $JTM_GROUP

cp $DEPLOY_DIR/supervisord-config-jaws $SUPERVISOR_DIR/supervisord-jaws.conf
cp $DEPLOY_DIR/supervisord-config-jtm $SUPERVISOR_DIR/supervisord-jtm.conf

chgrp $JAWS_GROUP "$SUPERVISOR_DIR/supervisord-jaws.conf"
chmod 660 "$SUPERVISOR_DIR/supervisord-jaws.conf"
chgrp $JTM_GROUP "$SUPERVISOR_DIR/supervisord-jtm.conf"
chmod 660 "$SUPERVISOR_DIR/supervisord-jtm.conf"
