#!/bin/bash

set -eo pipefail

## DEFINE INSTALL VARS
SRC_DIR={{src_dir}}
INSTALL_DIR={{site.local.install_dir}}
JTM_WORKER_INSTALL_DIR={{site.local.jtm.worker_install_dir}}
CLIENT_INSTALL_DIR={{client.install_dir}}
JAWS_GROUP={{site.local.group_perms.jaws}}
JTM_GROUP={{site.local.group_perms.jtm}}
CONFIG_DIR=$INSTALL_DIR/config
DEPLOY_DIR=$INSTALL_DIR/deploy
SITE_DIR=$INSTALL_DIR/site
CENTRAL_DIR=$INSTALL_DIR/central
JTM_DIR=$INSTALL_DIR/jtm

## DELETE OLD WHEELS
rm -rf ./*/dist/*

## DELETE OLD VENVS
test -d $SITE_DIR && rm -rf $SITE_DIR
test -d $CENTRAL_DIR && rm -rf $CENTRAL_DIR
test -d $JTM_DIR && rm -rf $JTM_DIR
test -d $JTM_WORKER_INSTALL_DIR && rm -rf $JTM_WORKER_INSTALL_DIR
test -d $CLIENT_INSTALL_DIR && rm -rf $CLIENT_INSTALL_DIR

## MAKE VENVS
#module load python
cd $SRC_DIR
make pkg
python3 -m venv $SITE_DIR && \
  . $SITE_DIR/bin/activate && \
  pip install --upgrade pip && \
  pip install $SRC_DIR/rpc/dist/* && \
  pip install $SRC_DIR/site/dist/* && \
  deactivate
python3 -m venv $CENTRAL_DIR && \
  . $CENTRAL_DIR/bin/activate && \
  pip install --upgrade pip && \
  pip install $SRC_DIR/rpc/dist/* && \
  pip install $SRC_DIR/central/dist/* && \
  deactivate
python3 -m venv $JTM_DIR && \
  . $JTM_DIR/bin/activate && \
  pip install --upgrade pip && \
  pip install rpc/dist/* && \
  pip install $SRC_DIR/jtm/dist/* && \
  deactivate
python3 -m venv $JTM_WORKER_INSTALL_DIR && \
  . $JTM_WORKER_INSTALL_DIR/bin/activate && \
  pip install --upgrade pip && \
  pip install $SRC_DIR/rpc/dist/* && \
  pip install $SRC_DIR/jtm/dist/* && \
  deactivate
python3 -m venv $CLIENT_INSTALL_DIR && \
  . $CLIENT_INSTALL_DIR/bin/activate && \
  pip install --upgrade pip && \
  pip install $SRC_DIR/client/dist/* && \
  deactivate

## PERMISSIONS
function fix_perms() {
    local DIR=$1
    local GROUP=$2
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R $GROUP "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}

fix_perms $SITE_DIR $JAWS_GROUP
fix_perms $CENTRAL_DIR $JAWS_GROUP
fix_perms $JTM_DIR $JTM_GROUP
