GRANT ALL PRIVILEGES ON * . * TO 'jaws'@'%';
CREATE DATABASE IF NOT EXISTS jaws_cromwell_dev;
CREATE DATABASE IF NOT EXISTS jaws_local_dev;
CREATE DATABASE IF NOT EXISTS cromwell_local_dev;
CREATE DATABASE IF NOT EXISTS jaws_central_dev;
CREATE DATABASE IF NOT EXISTS jtm_local_dev;
