#!/bin/bash -l
# if ( c <= 18 && mem <= 740GB) then: shared else: exvivo
#SBATCH -c 36
#SBATCH --mem=1450G
#SBATCH -N 1
#SBATCH -C skylake
#SBATCH -A fungalp
#SBATCH -q jgi_exvivo
#SBATCH -t 72:00:00
#SBATCH --job-name=jaws_condor_xlarge_worker
#SBATCH --exclusive
#SBATCH -e /global/cscratch1/sd/jaws_jtm/condor/slurm/%N-%j.err
#SBATCH -o /global/cscratch1/sd/jaws_jtm/condor/slurm/%N-%j.out

srun -k -K0 /global/cfs/cdirs/jaws/condor/condor_worker.sh
# 72hr - 2min
sleep 259080 
srun -k -K0 /tahoma/mscjgi/condor/stop_worker.sh
exit
