#!/bin/sh
#SBATCH -q genepool_special
#SBATCH -C haswell
#SBATCH -A fungalp
#SBATCH -t 72:00:00
#SBATCH --job-name=jaws_condor_medium_worker
#SBATCH --exclusive
#SBATCH -e /global/cscratch1/sd/jaws_jtm/condor/slurm/%N-%j.err
#SBATCH -o /global/cscratch1/sd/jaws_jtm/condor/slurm/%N-%j.out

srun -k -K0 /global/cfs/cdirs/jaws/condor/condor_worker.sh
# 72hr - 2min
sleep 259080 
srun -k -K0 /tahoma/mscjgi/condor/stop_worker.sh
exit
