#!/bin/bash -l
#SBATCH --mem=1480G
#SBATCH -e /tahoma/mscjgi/scratch/slurm/%N-%j.err
#SBATCH -o /tahoma/mscjgi/scratch/slurm/%N-%j.out
##SBATCH --exclusive
#SBATCH --account=mscjgi
#SBATCH --nodes=1
#SBATCH --ntasks-per-node 36
#SBATCH --time=48:00:00
#SBATCH --job-name=jaws_condor_xlarge_worker

srun -k -K0 /tahoma/mscjgi/condor/condor_worker.sh
# 48hr - 2min
sleep 172680
srun -k -K0 /tahoma/mscjgi/condor/stop_worker.sh
exit
