#!/bin/bash -l
# if ( c <= 18 && mem <= 740GB) then: shared else: exvivo
#SBATCH -c 36
#SBATCH --mem=1450G
#SBATCH -N 1
#SBATCH -C skylake
#SBATCH -A fungalp
#SBATCH -q jgi_exvivo
#SBATCH -t 3:00:00
#SBATCH --job-name=jaws_condor_xlarge_worker
#SBATCH --exclusive
#SBATCH -e /global/cscratch1/sd/jaws_jtm/condor/%N-%j.err
#SBATCH -o /global/cscratch1/sd/jaws_jtm/condor/%N-%j.out

# normal
# srun -k -K0 /global/cfs/cdirs/jaws/condor/condor_worker.sh
# jgi_shared highmem node:  intended for jobs which require more than 128GB RAM but less than 768GB
# srun -k -K0 /global/cfs/cdirs/jaws/condor/condor_worker_highmem_jgi_shared.sh
# jgi_exvivo highmem node: 768G ~ 1.5T
srun -k -K0 /global/cfs/cdirs/jaws/condor/condor_worker_highmem_jgi_exvivo.sh
