#!/bin/sh 
#SBATCH -c 32
#SBATCH --mem=115G
#SBATCH -q genepool_special
#SBATCH -C haswell
#SBATCH -A fungalp
#SBATCH -t 6:00:00
#SBATCH --job-name=jaws_condor_normal_worker
#SBATCH --exclusive
#SBATCH -e /global/cscratch1/sd/jaws_jtm/condor/%N-%j.err
#SBATCH -o /global/cscratch1/sd/jaws_jtm/condor/%N-%j.out 

export FLAVOR=dynamic

srun -k -K0 /global/cfs/cdirs/jaws/condor/condor_worker.sh
#$HOME/condor_worker.sh
