# states should use concise names, all lowercase, and uses spaces (no camelCase, CAPS, or under_scores)
run_status_msg = {
    "created": "The Run was accepted and a run_id assigned",
    "upload queued": "The Run's input files are waiting to be transferred to the compute-site",
    "uploading": "Your Run's input files are being transferred to the compute-site",
    "upload failed": "The transfer of your run to the compute-site failed.",
    "upload inactive": "Globus transfer stalled.",
    "upload complete": "Your Run's input files have been transferred to the compute-site successfully",
    "ready": "The Run has been transferred to the compute-site",
    "missing input": "The run was uploaded but some of the required files were missing.",
    "submitted": "The run has been submitted to Cromwell and tasks should start to queue within moments",
    "submission failed": "The run was submitted to Cromwell but rejected due to invalid input.",
    "queued": "At least one task has requested resources but no tasks have started running yet",
    "running": "The run is being executed; you can check `task-status` for more detail",
    "succeeded": "The run has completed successfully",
    "failed": "The run has failed; see: `errors` and `metadata` for more detail",
    "finished": "The run has completed, metadata has been saved, and is ready to download",
    "aborting": "Your run is in the process of being canceled",
    "aborted": "The run was cancelled",
    "download queued": "Your Run's output files are waiting to be transferred from the compute-site",
    "downloading": "The Run's output files are being transferred from the compute-site",
    "download failed": "The Run's output files could not be transferred from the compute-site",
    "download inactive": "Globus transfer stalled.",
    "download complete": "Your Run's output (succeeded or failed) are available for you to `get`",
    "email sent": "Notification of run completion was sent via email",
    "done": "The run is complete."
}
