export JAWS_INSTALL_BASEDIR="/tahoma/mscjgi/jaws-install"
export JAWS_GLOBUS_EP="90170904-5642-11ed-89db-ede5bae4f491"
export JAWS_GLOBUS_HOST_PATH="/tahoma/mscjgi"
export JAWS_LOAD_PYTHON="module load python/3.8.1"
export JAWS_PYTHON="python"
export JAWS_GROUP="svc-jtm-manager"
export JAWS_USERS_GROUP="svc-jtm-manager"
export JAWS_SCRATCH_BASEDIR="/tahoma/mscjgi/scratch"
export JAWS_REF_DATA_DIR="/tahoma/mscjgi/refdata"
export JAWS_BIG_SCRATCH_DIR="/big_scratch"
export JAWS_MAX_RAM_GB=1480
export JAWS_MAX_CPU=36
export JAWS_PERFORMANCE_METRICS_SCRIPT="/tahoma/mscjgi/jaws-metrics/bin/pagurus"
export JAWS_PERFORMANCE_METRICS_DIR="/tahoma/mscjgi/jaws_jtm/monitoring-runs"
