#!/usr/bin/env bash

# This script defines variables constructed from other variables, in order to
# keep the number of configured variables to a minimum, and to
# keep the variable definitions largely in one place.
# Deployment scripts shall source this file.


## VALIDATE INPUT VARS
## print list of all missing vars (instead of exiting on first undefined var)
## exit with 1 if any vars are missing; 0 otherwise
REQUIRED_VARS="
JAWS_SITE
DEPLOYMENT_NAME
JAWS_DOCS_URL
JAWS_CENTRAL_HOST
JAWS_RMQ_HOST
JAWS_RMQ_PORT
JAWS_GLOBUS_CLIENT_ID
CROMWELL_VERSION
CROMWELL_JAR_URL
WOMTOOL_JAR_URL
"
RESULT=0
echo "VALIDATING REQUIRED VARS"
for VAR in $REQUIRED_VARS; do
  if [[ -z ${!VAR} ]]; then
    echo "Missing env var: $VAR">&2
    RESULT=1
  fi
  echo "... $VAR : OK"
done
[ $RESULT -eq 0 ] || exit $RESULT

## DEPLOYMENT-SPECIFIC VARIABLES
echo "DEFINING DEPLOYMENT VARS"
function set_deployment_var {
  VAR_NAME="$1"
  SRC_VAR_NAME="${DEPLOYMENT_NAME}_${VAR_NAME}"
  if [ -z ${!SRC_VAR_NAME+xxx} ]; then
    echo "Missing env var: $SRC_VAR_NAME">&2
    exit 1
  fi
  VALUE="${!SRC_VAR_NAME}"
  echo "... $VAR_NAME"
  export $VAR_NAME
  printf -v "$VAR_NAME" "%s" "$VALUE"
}
DEPLOYMENT_VARS="
LOG_LEVEL
JAWS_SUPERVISOR_PORT
JAWS_AUTH_PORT
JAWS_REST_PORT
CROMWELL_PORT
"
for DEPLOYMENT_VAR in $DEPLOYMENT_VARS; do
  set_deployment_var $DEPLOYMENT_VAR
done


## SITE-SPECIFIC VARIABLES:
## This will define global vars with a SITE_ prefix, with values from variables referenced by the JAWS_SITE
## variable.  For instance, if JAWS_SITE="JGI", setting GLOBUS_EP site var will define a SITE_GLOBUS_EP var
## with the value from JGI_GLOBUS_EP.
## This allows the site installation scripts to use the SITE_* vars.
echo "DEFINING SITE VARS"
function set_site_var {
  VAR_NAME="$1"
  SRC_VAR_NAME="${JAWS_SITE}_${VAR_NAME}"
  if [ -z ${!SRC_VAR_NAME+xxx} ]; then
    echo "Missing env var: $SRC_VAR_NAME">&2
    exit 1
  fi
  SITE_VAR_NAME="SITE_${VAR_NAME}"
  VALUE="${!SRC_VAR_NAME}"
  echo "... $SITE_VAR_NAME"
  export $SITE_VAR_NAME
  printf -v "$SITE_VAR_NAME" "%s" "$VALUE"
}
SITE_VARS="
INSTALL_BASEDIR
CLIENT_INSTALL_BASEDIR
USER_GROUP
GLOBUS_EP
GLOBUS_HOST_PATH
PYTHON
LOAD_PYTHON
JAWS_GROUP
JTM_GROUP
CLIENT_GROUP
JAWS_SCRATCH_BASEDIR
JTM_SCRATCH_BASEDIR
CONTAINER_TMPDIR
REF_DATA_DIR
FAST_SCRATCH_DIR
BIG_SCRATCH_DIR
SUPERVISOR_HOST
CONTAINER_TYPE
CLUSTER_QOS
CLUSTER_PARTITION
CLUSTER_ACCOUNT
CLUSTER_CONSTRAINT
MAX_RAM_GB
RMQ_HOST
RMQ_PORT
RMQ_PW
HTCONDOR_INSTALL
HTCONDOR_MASTER_CONFIG
MONITOR_RMQ_HOST
MONITOR_RMQ_PORT
PERFORMANCE_METRICS_DIR
PERFORMANCE_METRICS_SCRIPT
PERFORMANCE_METRICS_CLEANUP
"
for SITE_VAR in $SITE_VARS; do
  set_site_var $SITE_VAR
done


## DEFINE VARS FROM OTHER VARS
echo "DEFINING PATHS"
export INSTALL_DIR="$SITE_INSTALL_BASEDIR/jaws-$DEPLOYMENT_NAME"
export CONFIG_DIR="$INSTALL_DIR/configs"
export SHIM_DIR="$INSTALL_DIR/shims"
export LOGS_DIR="$INSTALL_DIR/logs"
export SUPERVISOR_DIR="$SITE_INSTALL_BASEDIR/jaws-supervisord-$DEPLOYMENT_NAME"
if [[ "$SITE_CLIENT_INSTALL_BASEDIR" ]]; then
    export SITE_CLIENT_INSTALL_DIR="$SITE_CLIENT_INSTALL_BASEDIR/jaws-$DEPLOYMENT_NAME"
    export SITE_WOMTOOL_JAR="$SITE_CLIENT_INSTALL_DIR/womtool.jar"
else
    export SITE_CLIENT_INSTALL_DIR=""
    export SITE_WOMTOOL_JAR=""
fi
if [[ $SITE_JAWS_SCRATCH_BASEDIR =~ ^s3:\/\/ ]]; then
    # EACH AWS DEPLOYMENT HAS A SEPARATE S3 BUCKET
    export SITE_JAWS_SCRATCH_DIR="${SITE_JAWS_SCRATCH_BASEDIR}-${DEPLOYMENT_NAME}"
    export SITE_JTM_SCRATCH_DIR="${SITE_JAWS_SCRATCH_BASEDIR}-${DEPLOYMENT_NAME}"
else
    # EACH SERVER DEPLOYMENT HAS A SEPARATE NFS SUBDIR
    export SITE_JAWS_SCRATCH_DIR="$SITE_JAWS_SCRATCH_BASEDIR/jaws-$DEPLOYMENT_NAME"
    export SITE_JTM_SCRATCH_DIR="$SITE_JTM_SCRATCH_BASEDIR/jaws-$DEPLOYMENT_NAME"
fi

# Folders for Run inputs and downloads from other jaws-sites
export SITE_INPUTS_DIR="$SITE_JAWS_SCRATCH_DIR/inputs"
export SITE_DOWNLOADS_DIR="$SITE_JAWS_SCRATCH_DIR/downloads"

# Cromwell-related dirs
export SITE_CROMWELL_TMPDIR="$SITE_JTM_SCRATCH_DIR/cromwell-tmp"
export SITE_CROMWELL_JAR="$INSTALL_DIR/cromwell.jar"
export SITE_CONTAINERS_PULLDIR="$SITE_JTM_SCRATCH_BASEDIR/${SITE_CONTAINER_TYPE}_files"
export SITE_CONTAINERS_TMPDIR="$SITE_CONTAINER_TMPDIR/${SITE_CONTAINER_TYPE}_files"
export CROMWELL_WORKFLOW_LOGS_DIR="$LOGS_DIR/cromwell-workflow-logs"
export CROMWELL_EXECUTIONS_DIR="$SITE_JTM_SCRATCH_DIR/cromwell-executions"

# Performance metrics
export SITE_PERFORMANCE_METRICS_SCRIPT="$INSTALL_DIR/site/bin/pagurus"

# Globus has some rules about how paths are interpreted, depending on how the endpoint is configured.
[[ ${SITE_GLOBUS_ROOT_DIR:-1} == "/" ]] || SITE_GLOBUS_ROOT_DIR="$SITE_GLOBUS_ROOT_DIR/"

# virtual envs
export SITE_VENV_DIR="$INSTALL_DIR/site"


## CREATE DIRS AND SET GROUP AND PERMISSIONS
## - there are expected to be "jaws" and "jtm" users
## - "jaws" user belongs to "jaws" and "jtm" groups
## - "jtm" user belongs to "jtm" group and no others for security purposes
## - users don't belong to either "jaws" or "jtm" groups (protected)
function setup_dir {
  local DIR="$1"
  local GROUP="$2"
  local PERMS="$3"
  [[ -z $DIR ]] && echo "missing DIR" && exit 1
  [[ -z $GROUP ]] && echo "missing GROUP" && exit 1
  echo "... $DIR"
  test -d "$DIR" || mkdir -p "$DIR"
  chgrp "$GROUP" "$DIR"
  chmod "$PERMS" "$DIR"
}
echo "CREATING PATHS"
INSTALL_DIRS="
INSTALL_DIR
CONFIG_DIR
SHIM_DIR
LOGS_DIR
SUPERVISOR_DIR
SITE_CONTAINERS_PULLDIR
SITE_CONTAINERS_TMPDIR
SITE_JAWS_SCRATCH_DIR
SITE_CROMWELL_TMPDIR
CROMWELL_WORKFLOW_LOGS_DIR
"
for DIR in $INSTALL_DIRS; do
  setup_dir "${!DIR}" "$SITE_JTM_GROUP" 770
done

setup_dir "$SITE_JTM_SCRATCH_DIR" "$SITE_JTM_GROUP" 775
setup_dir "$SITE_INPUTS_DIR" "$SITE_JTM_GROUP" 777
setup_dir "$SITE_DOWNLOADS_DIR" "$SITE_CLIENT_GROUP" 2775
setup_dir "$CROMWELL_EXECUTIONS_DIR" "$SITE_JTM_GROUP" 775

