#!/bin/bash

# There is only one jaws-central deployment, while there may be several jaws-sites.
echo "BEGIN deploy-central"

function fix_perms() {
    local GROUP="$1"
    local DIR="$2"
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R "$GROUP" "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}

## VERIFY REQUIRED VARS ARE DEFINED
# If any env are undefined, try sourcing the setup script and check again.
# Exits if any required var is undefined.
REQUIRED_VARS="
JAWS_CENTRAL_DB_HOST
JAWS_CENTRAL_DB_PORT
JAWS_CENTRAL_DB_PW
JAWS_CENTRAL_RMQ_PW
JGI_RMQ_PW
CORI_RMQ_PW
CENTRAL_SUPERVISOR_HOST
CENTRAL_SUPERVISORD_PW
CENTRAL_JAWS_GROUP
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [ -z ${!VAR+xxx} ]; then
    echo "Missing env var, $VAR; sourcing setup script..."
    source ./test/integration/define-env
    RESULT=1
    break
  fi
done
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR">&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1

## DEPLOYMENT-SPECIFIC VARIABLES
echo "DEFINING DEPLOYMENT VARS"
function set_deployment_var {
  VAR_NAME="$1"
  SRC_VAR_NAME="${DEPLOYMENT_NAME}_${VAR_NAME}"
  if [ -z ${!SRC_VAR_NAME+xxx} ]; then
    echo "Missing env var: $SRC_VAR_NAME">&2
    exit 1
  fi
  VALUE="${!SRC_VAR_NAME}"
  echo "... $VAR_NAME"
  export $VAR_NAME
  printf -v "$VAR_NAME" "%s" "$VALUE"
}
DEPLOYMENT_VARS="
LOG_LEVEL
JAWS_SUPERVISOR_PORT
JAWS_AUTH_PORT
JAWS_REST_PORT"
for DEPLOYMENT_VAR in $DEPLOYMENT_VARS; do
  set_deployment_var $DEPLOYMENT_VAR
done

# DEFINE PATHS
echo "DEFINING PATHS"
export INSTALL_DIR="$CENTRAL_INSTALL_BASEDIR/jaws-$DEPLOYMENT_NAME"
export CONFIG_DIR="$INSTALL_DIR/configs"
export SHIM_DIR="$INSTALL_DIR/shims"
export LOGS_DIR="$INSTALL_DIR/logs"
export SUPERVISOR_DIR="$CENTRAL_INSTALL_BASEDIR/jaws-supervisord-$DEPLOYMENT_NAME"

#### SUPERVISORD

## CREATE DIRS
test -d $SUPERVISOR_DIR || mkdir $SUPERVISOR_DIR
chgrp $CENTRAL_JAWS_GROUP $SUPERVISOR_DIR
chmod 770 $SUPERVISOR_DIR

[[ -d $SUPERVISOR_DIR/bin ]] || mkdir $SUPERVISOR_DIR/bin
[[ -f $SUPERVISOR_DIR/venv/bin/activate ]] || $SITE_PYTHON -m venv $SUPERVISOR_DIR/venv
chgrp -R $CENTRAL_JAWS_GROUP $SUPERVISOR_DIR/{bin,venv}

source $SUPERVISOR_DIR/venv/bin/activate

function not_available() {
  command -v $1 >/dev/null 2>&1
}

not_available "supervisord" || $SITE_PYTHON_PIP install supervisor

function generate_shim() {
prog=$1
cat <<EOM > $SUPERVISOR_DIR/bin/$prog
#!/usr/bin/env bash

source $SUPERVISOR_DIR/venv/bin/activate

$prog \$@
EOM
chmod +x $SUPERVISOR_DIR/bin/$prog
}

generate_shim supervisord
generate_shim supervisorctl

fix_perms "$SITE_JTM_GROUP" "$SUPERVISOR_DIR"

cat << EOM > $SUPERVISOR_DIR/supervisord-jaws.conf
[inet_http_server]
port=0.0.0.0:$JAWS_SUPERVISOR_PORT
username=jaws
password=$CENTRAL_SUPERVISORD_PW

[supervisord]
logfile=$SUPERVISOR_DIR/jaws-log
logfile_maxbytes=50MB
logfile_backups=2
loglevel=info
pidfile=$SUPERVISOR_DIR/jaws-pidfile
nodaemon=false
minfds=1024
minprocs=200
identifier=supervisor-jaws-$DEPLOYMENT_NAME
directory=$SUPERVISOR_DIR

; The rpcinterface:supervisor section must remain in the config file for
; RPC (supervisorctl/web interface) to work.  Additional interfaces may be
; added by defining them in separate [rpcinterface:x] sections.
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=$CENTRAL_SUPERVISOR_HOST:$JAWS_SUPERVISOR_PORT
username=jaws
password=$CENTRAL_SUPERVISORD_PW
prompt=supervisor-jaws-$DEPLOYMENT_NAME

;----- Program Section

[program:jaws-central-rest]
command=$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected

[program:jaws-central-rpc]
command=$SHIM_DIR/jaws-central-rpc-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected

[program:jaws-central-auth]
command=$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected

[group:jaws-$DEPLOYMENT_NAME]
programs=jaws-central-auth,jaws-central-rest,jaws-central-rpc
priority=999
EOM

chgrp "$CENTRAL_JAWS_GROUP" "$SUPERVISOR_DIR/supervisord-jaws.conf"
chmod 660 "$SUPERVISOR_DIR/supervisord-jaws.conf"

## DELETE OLD VENV
test -d "$INSTALL_DIR/central" && rm -rf "$INSTALL_DIR/central"

## MAKE VENV
make pkg
$CENTRAL_PYTHON -m venv "$INSTALL_DIR/central" && \
  . "$INSTALL_DIR/central/bin/activate" && \
  $CENTRAL_PYTHON_PIP install rpc/dist/* && \
  $CENTRAL_PYTHON_PIP install central/dist/* && \
  deactivate

## FIX PERMISSIONS
fix_perms "$CENTRAL_JAWS_GROUP" "$INSTALL_DIR/central"

## GENERATE CONFIG
CONF=""

function set_site_var {
  local A_SITE="$1"
  VAR_NAME="$2"
  SRC_VAR_NAME="${A_SITE}_${VAR_NAME}"
  SITE_VAR_NAME="A_SITE_${VAR_NAME}"
  VALUE="${!SRC_VAR_NAME}"
  echo "... $SITE_VAR_NAME"
  export $SITE_VAR_NAME
  printf -v "$SITE_VAR_NAME" "%s" "$VALUE"
}
for A_SITE in $JAWS_SITES; do
  set_site_var "$A_SITE" "GLOBUS_EP"
  set_site_var "$A_SITE" "GLOBUS_ROOT_DIR"
  set_site_var "$A_SITE" "JTM_SCRATCH_BASEDIR"
  set_site_var "$A_SITE" "MAX_RAM_GB"
  A_SITE_JTM_SCRATCH_DIR="$A_SITE_JTM_SCRATCH_BASEDIR/jaws-$DEPLOYMENT_NAME"
  A_SITE_UPLOADS_DIR="$A_SITE_JTM_SCRATCH_DIR/uploads"
  [[ ${A_SITE_GLOBUS_ROOT_DIR: -1} == "/" ]] || A_SITE_GLOBUS_ROOT_DIR="$A_SITE_GLOBUS_ROOT_DIR/"
  if [[ $A_SITE_GLOBUS_ROOT_DIR == "/" ]]; then
    A_SITE_UPLOADS_SUBDIR=$A_SITE_UPLOADS_DIR
  else
    A_SITE_UPLOADS_SUBDIR=${A_SITE_UPLOADS_DIR#$A_SITE_GLOBUS_ROOT_DIR}
  fi
  CONF="$CONF
[SITE:$A_SITE]
user = jaws
password = $JAWS_CENTRAL_RMQ_PW
host = $JAWS_CENTRAL_RMQ_HOST
port = $JAWS_CENTRAL_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = JAWS_$A_SITE
globus_endpoint = $A_SITE_GLOBUS_EP
globus_basepath = $A_SITE_GLOBUS_ROOT_DIR
uploads_subdir = $A_SITE_UPLOADS_SUBDIR
max_ram_gb = $A_SITE_MAX_RAM_GB
"
done

cat << EOM > $CONFIG_DIR/jaws-central.conf
[JAWS]
name = $DEPLOYMENT_NAME
version = $JAWS_VERSION
docs_url = $JAWS_DOCS_URL
[DB]
dialect = mysql+mysqlconnector
host = $JAWS_CENTRAL_DB_HOST
port = $JAWS_CENTRAL_DB_PORT
user = jaws
password = $JAWS_CENTRAL_DB_PW
db = jaws_central_$DEPLOYMENT_NAME
[RPC_SERVER]
user = jaws
password = $JAWS_CENTRAL_RMQ_PW
host = $JAWS_CENTRAL_RMQ_HOST
port = $JAWS_CENTRAL_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = CENTRAL
num_threads = 5
max_retries = 3
[GLOBUS]
client_id = $JAWS_GLOBUS_CLIENT_ID
[HTTP]
auth_port = $JAWS_AUTH_PORT
rest_port = $JAWS_REST_PORT
$CONF
EOM

chgrp "$CENTRAL_JAWS_GROUP" "$CONFIG_DIR/jaws-central.conf"
chmod 660 "$CONFIG_DIR/jaws-central.conf"


## GENERATE SHIMS
cat <<EOM > $SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-auth.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL auth
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rest.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rest
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rpc-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rpc.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rpc
EOM

chgrp "$CENTRAL_JAWS_GROUP" "$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME"
chgrp "$CENTRAL_JAWS_GROUP" "$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME"
chmod 770 "$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME"
chmod 770 "$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME"

printf "END deploy-central\n\n"
