#!/bin/bash

echo "BEGIN deploy-central"

set -e

function fix_perms() {
    local GROUP=$1
    local DIR="$2"
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R $GROUP "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}


## VALIDATE ENV VARS
echo "CHECKING FOR REQUIRED ENV VARS"
REQUIRED_VARS="
DEPLOYMENT_NAME
JAWS_DB_HOST
JAWS_DB_PORT
JAWS_DB_PW
JAWS_EMAIL_USER
JAWS_EMAIL_PW
JAWS_RMQ_HOST
JAWS_RMQ_PORT
JAWS_RMQ_PW
CENTRAL_SUPERVISOR_HOST
CENTRAL_SUPERVISOR_PORT
CENTRAL_SUPERVISORD_PW
CENTRAL_JAWS_GROUP
CENTRAL_PYTHON
ES_HOST_ADDR
ES_HOST_PORT
ES_API_KEY
"
RESULT=0
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR">&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1


## INIT VARS
echo "DEFINING DEPLOYMENT VARS"
function set_deployment_var {
  VAR_NAME="$1"
  SRC_VAR_NAME="${DEPLOYMENT_NAME}_${VAR_NAME}"
  if [ -z ${!SRC_VAR_NAME+xxx} ]; then
    echo "Missing env var: $SRC_VAR_NAME">&2
    exit 1
  fi
  VALUE="${!SRC_VAR_NAME}"
  echo "... $VAR_NAME"
  export $VAR_NAME
  printf -v "$VAR_NAME" "%s" "$VALUE"
}
DEPLOYMENT_VARS="
LOG_LEVEL
JAWS_CENTRAL_SUPERVISOR_PORT
JAWS_AUTH_PORT
JAWS_REST_PORT"
for DEPLOYMENT_VAR in $DEPLOYMENT_VARS; do
  set_deployment_var $DEPLOYMENT_VAR
done

export INSTALL_DIR="$CENTRAL_INSTALL_BASEDIR/jaws-central-$DEPLOYMENT_NAME"
export CONFIG_DIR="$INSTALL_DIR/configs"
export SHIM_DIR="$INSTALL_DIR/shims"
export LOGS_DIR="$INSTALL_DIR/logs"
export SUPERVISOR_DIR="$CENTRAL_INSTALL_BASEDIR/jaws-central-supervisord-$DEPLOYMENT_NAME"


## CREATE FOLDERS
echo "CREATING PATHS"
function setup_dir {
  local DIR="$1"
  local GROUP="$2"
  local PERMS="$3"
  [[ -z $DIR ]] && echo "missing DIR" && exit 1
  [[ -z $GROUP ]] && echo "missing GROUP" && exit 1
  echo "... $DIR"
  test -d "$DIR" || mkdir -p "$DIR"
  chgrp "$GROUP" "$DIR"
  chmod "$PERMS" "$DIR"
}
INSTALL_DIRS="
INSTALL_DIR
CONFIG_DIR
SHIM_DIR
LOGS_DIR
SUPERVISOR_DIR
"
for DIR in $INSTALL_DIRS; do
  setup_dir "${!DIR}" "$CENTRAL_JAWS_GROUP" 770
done


## STOP SERVICE
echo "STOPPING SERVICES"
test -f $SUPERVISOR_DIR/supervisord-jaws-central.conf && $SUPERVISOR_DIR/bin/supervisorctl -c $SUPERVISOR_DIR/supervisord-jaws-central.conf stop \
jaws-central-$DEPLOYMENT_NAME:auth \
jaws-central-$DEPLOYMENT_NAME:rest \
jaws-central-$DEPLOYMENT_NAME:rpc \
jaws-central-$DEPLOYMENT_NAME:run-daemon


## DELETE OLD VERSION
echo "BUILDING jaws-central"
test -d "$INSTALL_DIR/central" && rm -rf "$INSTALL_DIR/central"


## MAKE NEW VERSION
$CENTRAL_PYTHON -m venv "$INSTALL_DIR/central"
source "$INSTALL_DIR/central/bin/activate"
pip install --upgrade pip
pip install wheel pytest flake8 gunicorn
test -d rpc/dist && rm -rf rpc/dist
test -d central/dist && rm -rf central/dist
make pkg-central
pip install rpc/dist/* && pip install central/dist/*
deactivate
fix_perms "$CENTRAL_JAWS_GROUP" "$INSTALL_DIR/central"


## GENERATE CONFIG
echo "GENERATE jaws-central CONFIG"
CONF=""
function set_site_var {
  local A_SITE="$1"
  VAR_NAME="$2"
  SRC_VAR_NAME="${A_SITE}_${VAR_NAME}"
  SITE_VAR_NAME="A_SITE_${VAR_NAME}"
  VALUE="${!SRC_VAR_NAME}"
  echo "... $SITE_VAR_NAME"
  export $SITE_VAR_NAME
  printf -v "$SITE_VAR_NAME" "%s" "$VALUE"
}
for A_SITE in $JAWS_SITES; do
  set_site_var "$A_SITE" "GLOBUS_EP"
  set_site_var "$A_SITE" "GLOBUS_HOST_PATH"
  set_site_var "$A_SITE" "JAWS_SCRATCH_BASEDIR"
  set_site_var "$A_SITE" "MAX_RAM_GB"
  if [[ $A_SITE_JAWS_SCRATCH_BASEDIR =~ ^s3:\/\/ ]]; then
    A_SITE_JAWS_SCRATCH_DIR="${A_SITE_JAWS_SCRATCH_BASEDIR}-${DEPLOYMENT_NAME}"
  else
    A_SITE_JAWS_SCRATCH_DIR="$A_SITE_JAWS_SCRATCH_BASEDIR/jaws-$DEPLOYMENT_NAME"
  fi
  A_SITE_INPUTS_DIR="$A_SITE_JAWS_SCRATCH_DIR/inputs"
  A_SITE_DOWNLOADS_DIR="$A_SITE_JAWS_SCRATCH_DIR/downloads"
  [[ ${A_SITE_GLOBUS_HOST_PATH: -1} == "/" ]] || A_SITE_GLOBUS_HOST_PATH="$A_SITE_GLOBUS_HOST_PATH/"
  CONF="$CONF
[SITE:$A_SITE]
user = jaws
password = $JAWS_RMQ_PW
host = $JAWS_RMQ_HOST
port = $JAWS_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = JAWS_$A_SITE
user_group = $A_SITE_USER_GROUP
globus_endpoint = $A_SITE_GLOBUS_EP
globus_host_path = $A_SITE_GLOBUS_HOST_PATH
inputs_dir = $A_SITE_INPUTS_DIR
downloads_dir = $A_SITE_DOWNLOADS_DIR
max_ram_gb = $A_SITE_MAX_RAM_GB
"
done

CONFIG_FILE="$CONFIG_DIR/jaws-central.conf"
cat << EOM > "$CONFIG_FILE"
[JAWS]
name = $DEPLOYMENT_NAME
version = $JAWS_VERSION
docs_url = $JAWS_DOCS_URL
[DB]
dialect = mysql+mysqlconnector
host = $JAWS_DB_HOST
port = $JAWS_DB_PORT
user = jaws
password = $JAWS_DB_PW
db = jaws_central_$DEPLOYMENT_NAME
[RPC_SERVER]
user = jaws
password = $JAWS_RMQ_PW
host = $JAWS_RMQ_HOST
port = $JAWS_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = CENTRAL
num_threads = 5
max_retries = 3
[GLOBUS]
client_id = $JAWS_GLOBUS_CLIENT_ID
client_secret = $JAWS_GLOBUS_CLIENT_SECRET
[HTTP]
auth_port = $JAWS_AUTH_PORT
rest_port = $JAWS_REST_PORT
[EMAIL]
server=$JAWS_EMAIL_SERVER
port=$JAWS_EMAIL_PORT
user=$JAWS_EMAIL_USER
password=$JAWS_EMAIL_PW
$CONF
[ELASTICSEARCH]
host=$ES_HOST_ADDR
port=$ES_HOST_PORT
api_key=$ES_API_KEY
[PERFORMANCE_METRICS]
index=performance_metrics
EOM
chmod 660 "$CONFIG_FILE" && chgrp "$CENTRAL_JAWS_GROUP" "$CONFIG_FILE"


## GENERATE SHIMS
SHIM_FILE="$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME"
cat <<EOM > "$SHIM_FILE"
#!/usr/bin/env bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8
source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-auth.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL auth
EOM
chmod 770 "$SHIM_FILE" && chgrp "$CENTRAL_JAWS_GROUP" "$SHIM_FILE"

SHIM_FILE="$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME"
cat <<EOM > "$SHIM_FILE"
#!/usr/bin/env bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8
source $INSTALL_DIR/central/bin/activate
exec jaws-central --log=$LOGS_DIR/central-rest.log --config=$CONFIG_DIR/jaws-central.conf --log-level=$LOG_LEVEL rest
EOM
chmod 770 "$SHIM_FILE" && chgrp "$CENTRAL_JAWS_GROUP" "$SHIM_FILE"

SHIM_FILE="$SHIM_DIR/jaws-central-rpc-$DEPLOYMENT_NAME"
cat <<EOM > "$SHIM_FILE"
#!/usr/bin/env bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8
source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rpc.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rpc
EOM
chmod 770 "$SHIM_FILE" && chgrp "$CENTRAL_JAWS_GROUP" "$SHIM_FILE"

SHIM_FILE="$SHIM_DIR/jaws-central-run-daemon-$DEPLOYMENT_NAME"
cat <<EOM > "$SHIM_FILE"
#!/usr/bin/env bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8
source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-run-daemon.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL run-daemon
EOM
chmod 770 "$SHIM_FILE" && chgrp "$CENTRAL_JAWS_GROUP" "$SHIM_FILE"

SHIM_FILE="$SHIM_DIR/jaws-central-report-daemon-$DEPLOYMENT_NAME"
cat <<EOM > "$SHIM_FILE"
#!/usr/bin/env bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8
source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-report-daemon.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL report-daemon
EOM
chmod 770 "$SHIM_FILE" && chgrp "$CENTRAL_JAWS_GROUP" "$SHIM_FILE"


### SUPERVISORD
echo "DEPLOY SUPERVISORD"
[[ -d $SUPERVISOR_DIR/bin ]] || mkdir $SUPERVISOR_DIR/bin
[[ -f $SUPERVISOR_DIR/venv/bin/activate ]] || $CENTRAL_PYTHON -m venv $SUPERVISOR_DIR/venv
chgrp -R $CENTRAL_JAWS_GROUP $SUPERVISOR_DIR/{bin,venv}

source $SUPERVISOR_DIR/venv/bin/activate

function not_available() {
  command -v $1 >/dev/null 2>&1
}

not_available "supervisord" || pip install supervisor

function generate_shim() {
prog=$1
cat <<EOM > $SUPERVISOR_DIR/bin/$prog
#!/usr/bin/env bash

source $SUPERVISOR_DIR/venv/bin/activate

$prog \$@
EOM
chmod +x $SUPERVISOR_DIR/bin/$prog
}

generate_shim supervisord
generate_shim supervisorctl

fix_perms "$CENTRAL_JAWS_GROUP" "$SUPERVISOR_DIR"

cat << EOM > $SUPERVISOR_DIR/supervisord-jaws-central.conf
[inet_http_server]
port=0.0.0.0:$JAWS_CENTRAL_SUPERVISOR_PORT
username=jaws
password=$CENTRAL_SUPERVISORD_PW

[supervisord]
logfile=$SUPERVISOR_DIR/jaws-log
logfile_maxbytes=50MB
logfile_backups=2
loglevel=info
pidfile=$SUPERVISOR_DIR/jaws-pidfile
nodaemon=false
minfds=1024
minprocs=200
identifier=supervisord-jaws-central-$DEPLOYMENT_NAME
directory=$SUPERVISOR_DIR

; The rpcinterface:supervisor section must remain in the config file for
; RPC (supervisorctl/web interface) to work.  Additional interfaces may be
; added by defining them in separate [rpcinterface:x] sections.
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=$CENTRAL_SUPERVISOR_HOST:$JAWS_CENTRAL_SUPERVISOR_PORT
username=jaws
password=$CENTRAL_SUPERVISORD_PW
prompt=supervisord-jaws-central-$DEPLOYMENT_NAME

;----- Program Section

[program:rest]
command=$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=10
autorestart=unexpected

[program:rpc]
command=$SHIM_DIR/jaws-central-rpc-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=10
autorestart=unexpected

[program:run-daemon]
command=$SHIM_DIR/jaws-central-run-daemon-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=10
autorestart=unexpected

[program:report-daemon]
command=$SHIM_DIR/jaws-central-report-daemon-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=10
autorestart=unexpected

[program:auth]
command=$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=10
autorestart=unexpected

[group:jaws-central-$DEPLOYMENT_NAME]
programs=auth,rest,rpc,run-daemon
priority=999
EOM

fix_perms "$CENTRAL_JAWS_GROUP" "$SUPERVISOR_DIR/supervisord-jaws-central.conf"

## START SERVICES
echo "STARTING SERVICES"
test -f $SUPERVISOR_DIR/supervisord-jaws-central.conf && $SUPERVISOR_DIR/bin/supervisorctl -c $SUPERVISOR_DIR/supervisord-jaws-central.conf start \
jaws-central-$DEPLOYMENT_NAME:*

## DONE
printf "END deploy-central\n\n"
