#!/usr/bin/env bash

echo "BEGIN deploy-supervisord"

## VERIFY REQUIRED VARS ARE DEFINED
# If any env are undefined, try sourcing the setup script and check again.
# Exits if any required var is undefined.
REQUIRED_VARS="
SUPERVISOR_DIR
SITE_PYTHON
SITE_PYTHON_PIP
SITE_JAWS_GROUP
SITE_CROMWELL_GROUP
DEPLOYMENT_NAME
SHIM_DIR
JAWS_SUPERVISORD_PW
JAWS_SUPERVISOR_PORT
CROMWELL_SUPERVISOR_PORT
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [ -z ${!VAR+xxx} ]; then
    echo "Missing env var, $VAR; sourcing setup script..."
    source ./test/integration/define-env
    RESULT=1
    break
  fi
done
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR">&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1

## CREATE DIRS
test -d $SUPERVISOR_DIR || mkdir $SUPERVISOR_DIR
chgrp $SITE_CROMWELL_GROUP $SUPERVISOR_DIR
chmod 770 $SUPERVISOR_DIR

#$LOAD_SITE_PYTHON
module load python
[[ -d $SUPERVISOR_DIR/bin ]] || mkdir $SUPERVISOR_DIR/bin
[[ -f $SUPERVISOR_DIR/venv/bin/activate ]] || $SITE_PYTHON -m venv $SUPERVISOR_DIR/venv
chgrp -R $SITE_CROMWELL_GROUP $SUPERVISOR_DIR/{bin,venv}

source $SUPERVISOR_DIR/venv/bin/activate

function not_available() {
  command -v $1 >/dev/null 2>&1
}

not_available "supervisord" || $SITE_PYTHON_PIP install supervisor

function generate_shim() {
prog=$1
cat <<EOM > $SUPERVISOR_DIR/bin/$prog
#!/usr/bin/env bash

source $SUPERVISOR_DIR/venv/bin/activate

$prog \$@
EOM
chmod +x $SUPERVISOR_DIR/bin/$prog
}

generate_shim supervisord
generate_shim supervisorctl

function fix_perms() {
    local GROUP="$1"
    local DIR="$2"
    chmod -R 770 "$DIR"
    chgrp -R "$GROUP" "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}

fix_perms "$SITE_CROMWELL_GROUP" "$SUPERVISOR_DIR"

JAWS_PROGRAMS="jaws-site-daemon,jaws-site-local-rpc,jaws-site-central-rpc"
SUPERVISOR_JAWS_CONF="
[inet_http_server]
port=0.0.0.0:$JAWS_SUPERVISOR_PORT
username=jaws
password=$JAWS_SUPERVISORD_PW

[supervisord]
logfile=$SUPERVISOR_DIR/jaws-log
logfile_maxbytes=50MB
logfile_backups=2
loglevel=info
pidfile=$SUPERVISOR_DIR/jaws-pidfile
nodaemon=false
minfds=1024
minprocs=200
identifier=supervisor-jaws-$DEPLOYMENT_NAME
directory=$SUPERVISOR_DIR

; The rpcinterface:supervisor section must remain in the config file for
; RPC (supervisorctl/web interface) to work.  Additional interfaces may be
; added by defining them in separate [rpcinterface:x] sections.
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=$SITE_SUPERVISOR_HOST:$JAWS_SUPERVISOR_PORT
username=jaws
password=$JAWS_SUPERVISORD_PW
prompt=supervisor-jaws-$DEPLOYMENT_NAME

;----- Program Section

[program:jaws-site-daemon]
command=$SHIM_DIR/jaws-site-daemon-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected

[program:jaws-site-local-rpc]
command=$SHIM_DIR/jaws-site-local-rpc-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected

[program:jaws-site-central-rpc]
command=$SHIM_DIR/jaws-site-central-rpc-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected
"

if [[ -n $DEPLOY_JAWS_CLIENT ]]; then
  SUPERVISOR_JAWS_CONF="$SUPERVISOR_JAWS_CONF

[program:jaws-deploy-client]
command=$SHIM_DIR/jaws-deploy-client-$DEPLOYMENT_NAME
numprocs=1
startsecs=0
startretries=0
autorestart=false
"
  JAWS_PROGRAMS="$JAWS_PROGRAMS,jaws-deploy-client"
fi

if [[ -n "$DEPLOY_JAWS_CENTRAL" ]]; then
  SUPERVISOR_JAWS_CONF="$SUPERVISOR_JAWS_CONF

[program:jaws-central-rest]
command=$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected

[program:jaws-central-rpc]
command=$SHIM_DIR/jaws-central-rpc-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected

[program:jaws-central-auth]
command=$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME
numprocs=1
startsecs=3
startretries=3
autorestart=unexpected
"
  JAWS_PROGRAMS="$JAWS_PROGRAMS,jaws-central-auth,jaws-central-rest,jaws-central-rpc"
fi

cat << EOM > $SUPERVISOR_DIR/supervisord-jaws.conf
$SUPERVISOR_JAWS_CONF

[group:jaws-$DEPLOYMENT_NAME]
programs=$JAWS_PROGRAMS
priority=999
EOM


## CROMWELL SUPERVISOR CONF

cat << EOM > $SUPERVISOR_DIR/supervisord-cromwell.conf
[inet_http_server]
port=0.0.0.0:$CROMWELL_SUPERVISOR_PORT
username=jaws
password=$JAWS_SUPERVISORD_PW

[supervisord]
logfile=$SUPERVISOR_DIR/worker-log
logfile_maxbytes=50MB
logfile_backups=2
loglevel=info
pidfile=$SUPERVISOR_DIR/worker-pidfile
nodaemon=false
minfds=1024
minprocs=200
identifier=supervisor-cromwell-$DEPLOYMENT_NAME
directory=$SUPERVISOR_DIR

; The rpcinterface:supervisor section must remain in the config file for
; RPC (supervisorctl/web interface) to work.  Additional interfaces may be
; added by defining them in separate [rpcinterface:x] sections.

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=$SITE_SUPERVISOR_HOST:$CROMWELL_SUPERVISOR_PORT
username=jaws
password=$JAWS_SUPERVISORD_PW
prompt=supervisor-cromwell-$DEPLOYMENT_NAME

;----- Program Section

[program:jaws-cromwell]
command=$SHIM_DIR/jaws-cromwell-$DEPLOYMENT_NAME
numprocs=1
startsecs=10
startretries=3
autorestart=unexpected

[program:jaws-deploy-worker]
command=$SHIM_DIR/jaws-deploy-worker-$DEPLOYMENT_NAME
numprocs=1
startsecs=0
startretries=0
autorestart=false

[group:jaws-$DEPLOYMENT_NAME]
programs=jaws-cromwell,jaws-deploy-worker
priority=999
EOM

chgrp "$SITE_JAWS_GROUP" "$SUPERVISOR_DIR/supervisord-jaws.conf"
chmod 660 "$SUPERVISOR_DIR/supervisord-jaws.conf"
chgrp "$SITE_CROMWELL_GROUP" "$SUPERVISOR_DIR/supervisord-cromwell.conf"
chmod 660 "$SUPERVISOR_DIR/supervisord-cromwell.conf"

printf "END deploy-supervisord\n\n"
