#!/bin/bash -l

SITE_LOAD_PYTHON="module load python/3.8"
DEPLOYMENT_NAME="dev"
SITE_CLIENT_INSTALL_DIR="/bin/jaws"

cat << EOM > test.sh
# source this file to activate jaws-$DEPLOYMENT_NAME

if [[ "$SITE_LOAD_PYTHON" == module* ]]; then
  module list 2>/dev/null
  if [ \$? == 0 ]; then
    if [[ ! -z \`module list python 2>&1 | grep python\` ]]; then
      echo "Warning: a python module is already loaded" 1>&2
    fi
  fi
  module unload python
fi
$SITE_LOAD_PYTHON
source "$SITE_CLIENT_INSTALL_DIR/bin/activate"

export JAWS_CLIENT_CONFIG=$SITE_CLIENT_INSTALL_DIR/jaws-$DEPLOYMENT_NAME.conf
export JAWS_USER_CONFIG=~/jaws.conf

source $SITE_CLIENT_INSTALL_DIR/jaws-autocomplete-$DEPLOYMENT_NAME.sh

echo "jaws-$DEPLOYMENT_NAME activated; see \"jaws --help\" for more."
EOM
