#!/bin/bash

# There is only one jaws-central deployment, while there may be several jaws-sites.

## VALIDATE AND SETUP ENV
source ./test/integration/define-env

## VALIDATE ADDITIONAL VARS SPECIFIC TO CENTRAL
REQUIRED_VARS="
JAWS_CENTRAL_DB_HOST
JAWS_CENTRAL_DB_PORT
JAWS_CENTRAL_DB_PW
JAWS_CENTRAL_RMQ_PW
JGI_RMQ_PW
CORI_RMQ_PW
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [[ -z ${!VAR} ]]; then
    echo "Missing env var: $VAR">&2
    RESULT=1
  fi
done
[ $RESULT -eq 0 ] || exit $RESULT

## DEFINE ADDITIONAL VARS SPECIFIC TO CENTRAL

## DELETE OLD VENV
test -d "$INSTALL_DIR/central" && rm -rf "$INSTALL_DIR/central"

## MAKE VENV
#$LOAD_SITE_PYTHON
module load python
make pkg
$SITE_PYTHON -m venv "$INSTALL_DIR/central" && \
  . "$INSTALL_DIR/central/bin/activate" && \
  $SITE_PYTHON_PIP install rpc/dist/* && \
  $SITE_PYTHON_PIP install central/dist/* && \
  deactivate

## FIX PERMISSIONS
function fix_perms() {
    local GROUP="$1"
    local DIR="$2"
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R "$GROUP" "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}
fix_perms "$SITE_JAWS_GROUP" "$INSTALL_DIR/central"

## GENERATE CONFIG
CONF=""

function set_site_var {
  local A_SITE="$1"
  VAR_NAME="$2"
  SRC_VAR_NAME="${A_SITE}_${VAR_NAME}"
  SITE_VAR_NAME="A_SITE_${VAR_NAME}"
  VALUE="${!SRC_VAR_NAME}"
  echo "... $SITE_VAR_NAME"
  export $SITE_VAR_NAME
  printf -v "$SITE_VAR_NAME" "%s" "$VALUE"
}
for A_SITE in $JAWS_SITES; do
  set_site_var "$A_SITE" "GLOBUS_EP"
  set_site_var "$A_SITE" "GLOBUS_ROOT_DIR"
  set_site_var "$A_SITE" "JTM_SCRATCH_BASEDIR"
  set_site_var "$A_SITE" "MAX_RAM_GB"
  A_SITE_JTM_SCRATCH_DIR="$A_SITE_JTM_SCRATCH_BASEDIR/jaws-$DEPLOYMENT_NAME"
  A_SITE_UPLOADS_DIR="$A_SITE_JTM_SCRATCH_DIR/uploads"
  [[ ${A_SITE_GLOBUS_ROOT_DIR: -1} == "/" ]] || A_SITE_GLOBUS_ROOT_DIR="$A_SITE_GLOBUS_ROOT_DIR/"
  if [[ $A_SITE_GLOBUS_ROOT_DIR == "/" ]]; then
    A_SITE_UPLOADS_SUBDIR=$A_SITE_UPLOADS_DIR
  else
    A_SITE_UPLOADS_SUBDIR=${A_SITE_UPLOADS_DIR#$A_SITE_GLOBUS_ROOT_DIR}
  fi
  CONF="$CONF
[SITE:$A_SITE]
user = jaws
password = $JAWS_CENTRAL_RMQ_PW
host = $JAWS_CENTRAL_RMQ_HOST
port = $JAWS_CENTRAL_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = $A_SITE
globus_endpoint = $A_SITE_GLOBUS_EP
globus_basepath = $A_SITE_GLOBUS_ROOT_DIR
uploads_subdir = $A_SITE_UPLOADS_SUBDIR
max_ram_gb = $A_SITE_MAX_RAM_GB
"
done

cat << EOM > $CONFIG_DIR/jaws-central.conf
[JAWS]
name = $DEPLOYMENT_NAME
version = $JAWS_VERSION
docs_url = $JAWS_DOCS_URL
[DB]
dialect = mysql+mysqlconnector
host = $JAWS_CENTRAL_DB_HOST
port = $JAWS_CENTRAL_DB_PORT
user = jaws
password = $JAWS_CENTRAL_DB_PW
db = jaws_central_$DEPLOYMENT_NAME
[RPC_SERVER]
user = jaws
password = $JAWS_CENTRAL_RMQ_PW
host = $JAWS_CENTRAL_RMQ_HOST
port = $JAWS_CENTRAL_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = CENTRAL
num_threads = 5
max_retries = 3
[GLOBUS]
client_id = $JAWS_GLOBUS_CLIENT_ID
[HTTP]
auth_port = $JAWS_AUTH_PORT
rest_port = $JAWS_REST_PORT
$CONF
EOM

chgrp "$SITE_JAWS_GROUP" "$CONFIG_DIR/jaws-central.conf"
chmod 660 "$CONFIG_DIR/jaws-central.conf"


## GENERATE SHIMS
cat <<EOM > $SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-auth.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL auth
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rest.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rest
EOM

cat <<EOM > $SHIM_DIR/jaws-central-rpc-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/central/bin/activate
exec jaws-central --log $LOGS_DIR/central-rpc.log --config $CONFIG_DIR/jaws-central.conf --log-level $LOG_LEVEL rpc
EOM

chgrp "$SITE_JAWS_GROUP" "$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME"
chgrp "$SITE_JAWS_GROUP" "$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME"
chmod 770 "$SHIM_DIR/jaws-central-auth-$DEPLOYMENT_NAME"
chmod 770 "$SHIM_DIR/jaws-central-rest-$DEPLOYMENT_NAME"
