#!/bin/bash

# There is only one jaws-user deployment, while there may be several jaws-sites.
echo "BEGIN deploy-user"

## VERIFY REQUIRED VARS ARE DEFINED
# If any env are undefined, try sourcing the setup script and check again.
# Exits if any required var is undefined.
REQUIRED_VARS="
JAWS_CENTRAL_DB_HOST
JAWS_CENTRAL_DB_PORT
JAWS_CENTRAL_DB_PW
JAWS_CENTRAL_RMQ_PW
JGI_RMQ_PW
CORI_RMQ_PW
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [ -z ${!VAR+xxx} ]; then
    echo "Missing env var, $VAR; sourcing setup script..."
    source ./test/integration/define-env
    RESULT=1
    break
  fi
done
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR">&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1


## DELETE OLD VENV
test -d "$INSTALL_DIR/user" && rm -rf "$INSTALL_DIR/user"

## MAKE VENV
#$LOAD_SITE_PYTHON
module load python
make pkg
$SITE_PYTHON -m venv "$INSTALL_DIR/user" && \
  . "$INSTALL_DIR/user/bin/activate" && \
  $SITE_PYTHON_PIP install rpc/dist/* && \
  $SITE_PYTHON_PIP install user/dist/* && \
  deactivate

## FIX PERMISSIONS
function fix_perms() {
    local GROUP="$1"
    local DIR="$2"
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R "$GROUP" "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}
fix_perms "$SITE_JAWS_GROUP" "$INSTALL_DIR/user"

## GENERATE CONFIG
cat << EOM > $CONFIG_DIR/jaws-user.conf
[DB]
dialect = mysql+mysqlconnector
host = $JAWS_CENTRAL_DB_HOST
port = $JAWS_CENTRAL_DB_PORT
user = jaws
password = $JAWS_CENTRAL_DB_PW
db = jaws_user_$DEPLOYMENT_NAME
[RPC]
user = jaws
password = $JAWS_CENTRAL_RMQ_PW
host = $JAWS_CENTRAL_RMQ_HOST
port = $JAWS_CENTRAL_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = CENTRAL
num_threads = 5
max_retries = 3
[GLOBUS]
client_id = $JAWS_GLOBUS_CLIENT_ID
[HTTP]
auth_port = $JAWS_AUTH_PORT
$CONF
EOM

chgrp "$SITE_JAWS_GROUP" "$CONFIG_DIR/jaws-user.conf"
chmod 660 "$CONFIG_DIR/jaws-user.conf"


## GENERATE SHIMS
cat <<EOM > $SHIM_DIR/jaws-user-auth-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/user/bin/activate
exec jaws-user --log $LOGS_DIR/user.log --config $CONFIG_DIR/jaws-user.conf --log-level $LOG_LEVEL server
EOM

chgrp "$SITE_JAWS_GROUP" "$SHIM_DIR/jaws-user-$DEPLOYMENT_NAME"
chmod 770 "$SHIM_DIR/jaws-user-$DEPLOYMENT_NAME"

printf "END deploy-user\n\n"
