#!/bin/bash

# There is only one jaws-central deployment, while there may be several jaws-sites.
echo "BEGIN deploy-central"

## VERIFY REQUIRED VARS ARE DEFINED
# If any env are undefined, try sourcing the setup script and check again.
# Exits if any required var is undefined.
REQUIRED_VARS="
JAWS_AUTH_DB_HOST
JAWS_AUTH_DB_PORT
JAWS_AUTH_DB_PW
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [ -z ${!VAR+xxx} ]; then
    echo "Missing env var, $VAR; sourcing setup script..."
    source ./test/integration/define-env
    RESULT=1
    break
  fi
done
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR">&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1


## DELETE OLD VENV
test -d "$INSTALL_DIR/central" && rm -rf "$INSTALL_DIR/central"

## MAKE VENV
#$LOAD_SITE_PYTHON
module load python
make pkg
$SITE_PYTHON -m venv "$INSTALL_DIR/central" && \
  . "$INSTALL_DIR/central/bin/activate" && \
  $SITE_PYTHON_PIP install rpc/dist/* && \
  $SITE_PYTHON_PIP install central/dist/* && \
  deactivate

## FIX PERMISSIONS
function fix_perms() {
    local GROUP="$1"
    local DIR="$2"
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R "$GROUP" "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}
fix_perms "$SITE_JAWS_GROUP" "$INSTALL_DIR/central"

## GENERATE CONFIG
cat << EOM > $CONFIG_DIR/jaws-auth.conf
[DB]
dialect = mysql+mysqlconnector
host = $JAWS_AUTH_DB_HOST
port = $JAWS_AUTH_DB_PORT
user = jaws
password = $JAWS_AUTH_DB_PW
db = jaws_auth_$DEPLOYMENT_NAME
[HTTP]
auth_port = $JAWS_AUTH_PORT
EOM

chgrp "$SITE_JAWS_GROUP" "$CONFIG_DIR/jaws-auth.conf"
chmod 660 "$CONFIG_DIR/jaws-auth.conf"


## GENERATE SHIMS
cat <<EOM > $SHIM_DIR/jaws-auth-$DEPLOYMENT_NAME
#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PYTHONIOENCODING=utf-8

source $INSTALL_DIR/auth/bin/activate
exec jaws-auth --log $LOGS_DIR/auth.log --config $CONFIG_DIR/jaws-auth.conf --log-level $LOG_LEVEL server
EOM

chgrp "$SITE_JAWS_GROUP" "$SHIM_DIR/jaws-auth-$DEPLOYMENT_NAME"
chmod 770 "$SHIM_DIR/jaws-auth-$DEPLOYMENT_NAME"

printf "END deploy-auth\n\n"
