#!/usr/bin/env bash

. test/integration/libcommon

ensure_installed "python3" "gcc"
ensure_aws_creds
ensure_init

python3 -m venv venv
. venv/bin/activate

# install aws tools
pip install awscli

# install elasticluster
#TODO: specify version and not use master
git clone git://github.com/gc3-uzh-ch/elasticluster.git elasticluster
pip install -e elasticluster

fetch_elasticluster_data

elasticluster -c $(pwd)/elasticluster-data/config -s $(pwd)/elasticluster-data/storage stop --yes --force slurm
[[ $? == 0 ]] && aws s3 rm --recursive s3://jaws-testing/$PIPELINE_TAG/
