#!/usr/bin/env bash

echo "BEGIN generate-configs"

set -eo pipefail

## VERIFY REQUIRED VARS ARE DEFINED
# If any env are undefined, try sourcing the setup script and check again.
# Exits if any required var is undefined.
REQUIRED_VARS="
CONFIG_DIR
CROMWELL_PORT
DEPLOYMENT_NAME
JAWS_CENTRAL_RMQ_HOST
JAWS_CENTRAL_RMQ_PORT
JAWS_CENTRAL_RMQ_PW
JAWS_GLOBUS_CLIENT_ID
JAWS_SITE
SITE_CLUSTER_ACCOUNT
SITE_CLUSTER_CONSTRAINT
SITE_CLUSTER_PARTITION
SITE_CLUSTER_QOS
SITE_DB_HOST
SITE_DB_PORT
SITE_DB_PW
SITE_DOWNLOADS_SUBDIR
SITE_GLOBUS_DEFAULT_DIR
SITE_GLOBUS_EP
SITE_GLOBUS_ROOT_DIR
SITE_JAWS_GROUP
SITE_CROMWELL_GROUP
SITE_CROMWELL_SCRATCH_DIR
SITE_WORKER_INSTALL_DIR
SITE_RMQ_HOST
SITE_RMQ_PORT
SITE_RMQ_PW
SITE_UPLOADS_SUBDIR
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [ -z ${!VAR+xxx} ]; then
    echo "Missing env var, $VAR; sourcing setup script..."
    source ./test/integration/define-env
    RESULT=1
    break
  fi
done
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR">&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1

## WRITE CONFIG FILES
cat << EOM > $CONFIG_DIR/jaws-site.conf
[DB]
dialect = mysql+mysqlconnector
host = $SITE_DB_HOST
port = $SITE_DB_PORT
user = jaws
password = $SITE_DB_PW
db = jaws_$DEPLOYMENT_NAME
[LOCAL_RPC_SERVER]
user = jaws
password = $SITE_RMQ_PW
host = $SITE_RMQ_HOST
port = $SITE_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = SITE_$JAWS_SITE
num_threads = 5
max_retries = 3
[CENTRAL_RPC_SERVER]
user = jaws
password = $JAWS_CENTRAL_RMQ_PW
host = $JAWS_CENTRAL_RMQ_HOST
port = $JAWS_CENTRAL_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = JAWS_$JAWS_SITE
num_threads = 5
max_retries = 3
[CENTRAL_RPC_CLIENT]
user = jaws
password = $JAWS_CENTRAL_RMQ_PW
host = $JAWS_CENTRAL_RMQ_HOST
port = $JAWS_CENTRAL_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = CENTRAL
[GLOBUS]
client_id = $JAWS_GLOBUS_CLIENT_ID
endpoint_id = $SITE_GLOBUS_EP
root_dir = $SITE_GLOBUS_ROOT_DIR
default_dir = $SITE_GLOBUS_DEFAULT_DIR
[SITE]
id = $JAWS_SITE
uploads_subdirectory = $SITE_UPLOADS_SUBDIR
downloads_subdirectory = $SITE_DOWNLOADS_SUBDIR
[CROMWELL]
url = http://localhost:$CROMWELL_PORT
EOM

cat << EOM > $CONFIG_DIR/jaws-worker.conf
[LOCAL_RPC]
user = jaws
password = $SITE_RMQ_PW
host = $SITE_RMQ_HOST
port = $SITE_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = SITE_$JAWS_SITE
num_threads = 5
max_retries = 3
EOM


## SET PERMISSIONS
chgrp $SITE_JAWS_GROUP $CONFIG_DIR/*.conf
chgrp $SITE_CROMWELL_GROUP $CONFIG_DIR/jaws-worker.conf
chmod 660 $CONFIG_DIR/*

# Copy the jaws-worker config to NFS dir since workers will be on cluster node
cp "$CONFIG_DIR/jaws-worker.conf" "$SITE_WORKER_INSTALL_DIR/"
chgrp "$SITE_CROMWELL_GROUP" "$SITE_WORKER_INSTALL_DIR/jaws-worker.conf"
chmod 660 "$SITE_WORKER_INSTALL_DIR/jaws-worker.conf"

printf "END generate-configs\n\n"
