#!/bin/bash -l

echo "BEGIN generate-venvs"

set -eo pipefail

## VERIFY REQUIRED VARS ARE DEFINED
# If any env are undefined, try sourcing the setup script and check again.
# Exits if any required var is undefined.
REQUIRED_VARS="
SITE_JAWS_GROUP
SITE_JTM_GROUP
SITE_LOAD_PYTHON
SITE_PYTHON
SITE_VENV_DIR
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [ -z ${!VAR+xxx} ]; then
    echo "Missing env var, $VAR; sourcing setup script..."
    source ./test/integration/define-env
    RESULT=1
    break
  fi
done
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR">&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1


## DELETE OLD WHEELS
rm -rf ./*/dist/*

## DELETE OLD VENVS
test -d "$SITE_VENV_DIR" && rm -rf "$SITE_VENV_DIR"

## MAKE VENVS
[[ -n "$SITE_LOAD_PYTHON" ]] && $SITE_LOAD_PYTHON
make pkg
$SITE_PYTHON -m venv "$SITE_VENV_DIR" && \
  . "$SITE_VENV_DIR/bin/activate" && \
  pip install --upgrade pip && \
  pip install rpc/dist/* && \
  pip install site/dist/* && \
  deactivate

## PERMISSIONS
function fix_perms() {
    local DIR="$1"
    local GROUP=$2
    chmod -R a+rX "$DIR"
    chmod -R ug+rwX "$DIR"
    chgrp -R $GROUP "$DIR"
    find "$DIR" -type d -exec chmod g+s '{}' \;
}
fix_perms "$SITE_VENV_DIR" $SITE_JAWS_GROUP

# If pagurus is installed change the group so jaws_jtm can run it
test -d $SITE_VENV_DIR/bin/pagurus && chgrp $SITE_JTM_GROUP $SITE_VENV_DIR/bin/pagurus

printf "END generate-venvs\n\n"
