#!/usr/bin/env bash

echo "BEGIN generate-configs"

set -eo pipefail

## VERIFY REQUIRED VARS ARE DEFINED
# If any env are undefined, try sourcing the setup script and check again.
# Exits if any required var is undefined.
REQUIRED_VARS="
CONFIG_DIR
CROMWELL_EXECUTIONS_DIR
CROMWELL_PORT
DEPLOYMENT_NAME
JAWS_RMQ_HOST
JAWS_RMQ_PORT
JAWS_RMQ_PW
JAWS_GLOBUS_CLIENT_ID
JAWS_GLOBUS_CLIENT_SECRET
JAWS_SITE
JAWS_DEFAULT_CONTAINER
SITE_CLUSTER_ACCOUNT
SITE_CLUSTER_CONSTRAINT
SITE_CLUSTER_PARTITION
SITE_CLUSTER_QOS
JAWS_DB_HOST
JAWS_DB_PORT
JAWS_DB_PW
SITE_GLOBUS_EP
SITE_GLOBUS_HOST_PATH
SITE_JAWS_GROUP
SITE_INPUTS_DIR
SITE_DOWNLOADS_DIR
SITE_RMQ_HOST
SITE_RMQ_PORT
SITE_RMQ_PW
SITE_MONITOR_RMQ_HOST
SITE_MONITOR_RMQ_PORT
SITE_PERFORMANCE_METRICS_DIR
SITE_PERFORMANCE_METRICS_CLEANUP
SITE_PERFORMANCE_METRICS_SCRIPT
"
RESULT=0
for VAR in $REQUIRED_VARS; do
  if [ -z ${!VAR+xxx} ]; then
    echo "Missing env var, $VAR; sourcing setup script..."
    source ./test/integration/define-env
    RESULT=1
    break
  fi
done
if [[ $RESULT -ne 0 ]]; then
  RESULT=0
  for VAR in $REQUIRED_VARS; do
    if [ -z ${!VAR+xxx} ]; then
      echo "Missing env var: $VAR" >&2
      RESULT=1
    fi
  done
fi
[ $RESULT -eq 0 ] || exit 1

## WRITE CONFIG FILES
cat <<EOM >$CONFIG_DIR/jaws-site.conf
[DB]
dialect = mysql+mysqlconnector
host = $JAWS_DB_HOST
port = $JAWS_DB_PORT
user = jaws
password = $JAWS_DB_PW
db = jaws_${JAWS_SITE,,}_$DEPLOYMENT_NAME
[RPC_SERVER]
user = jaws
password = $JAWS_RMQ_PW
host = $JAWS_RMQ_HOST
port = $JAWS_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = JAWS_$JAWS_SITE
num_threads = 5
max_retries = 3
[CENTRAL_RPC_CLIENT]
user = jaws
password = $JAWS_RMQ_PW
host = $JAWS_RMQ_HOST
port = $JAWS_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = CENTRAL
[RUNS_ES_RPC_CLIENT]
user = jaws
password = $JAWS_RMQ_PW
host = $JAWS_RMQ_HOST
port = $JAWS_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = JAWS_RUNS_ES
[PERFORMANCE_METRICS_ES_RPC_CLIENT]
user = jaws
password = $JAWS_RMQ_PW
host = $JAWS_RMQ_HOST
port = $JAWS_RMQ_PORT
vhost = jaws_$DEPLOYMENT_NAME
queue = JAWS_PERF_METRICS_ES
[PERFORMANCE_METRICS]
done_dir = ${SITE_PERFORMANCE_METRICS_DIR}-${DEPLOYMENT_NAME}/done
processed_dir = ${SITE_PERFORMANCE_METRICS_DIR}-${DEPLOYMENT_NAME}/processed
running_dir = ${SITE_PERFORMANCE_METRICS_DIR}-${DEPLOYMENT_NAME}/running
cleanup_time = ${SITE_PERFORMANCE_METRICS_CLEANUP}
[GLOBUS]
client_id = $JAWS_GLOBUS_CLIENT_ID
client_secret = $JAWS_GLOBUS_CLIENT_SECRET
host_path = $SITE_GLOBUS_HOST_PATH
endpoint_id = $SITE_GLOBUS_EP
[SITE]
id = $JAWS_SITE
inputs_dir = $SITE_INPUTS_DIR
downloads_dir = $SITE_DOWNLOADS_DIR
default_container = $JAWS_DEFAULT_CONTAINER
[CROMWELL]
url = http://localhost:$CROMWELL_PORT
executions_dir = $CROMWELL_EXECUTIONS_DIR
[AWS]
aws_access_key_id = $AWS_ACCESS_KEY_ID
aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
s3_bucket = ABCD
EOM

## SET PERMISSIONS
chgrp $SITE_JAWS_GROUP $CONFIG_DIR/*.conf
chmod 660 $CONFIG_DIR/*
printf "END generate-configs\n\n"
